{
 "title": "MsSQL",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(mssql_deadlocks, job)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(mssql_io_stall_seconds, db)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mssql_deadlocks{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Kill connection error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mssql_kill_connection_errors{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mssql_memory_utilization_percentage{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mssql_buffer_cache_hit_ratio{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mssql_connections{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Disk available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mssql_disk_space_avaiable_bytes_total{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "% of Disk available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mssql_disk_space_avaiable_bytes_total{job=~\"$job\"})/sum(mssql_disk_space_total_bytes_total{job=~\"$job\"}) "
    }
   ]
  },
  {
   "title": "Database latency Read (LOG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_io_stall_seconds{operation=\"read\",type=\"LOG\",job=~\"$job\",db=~\"$db\"}[$interval])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database latency Write (LOG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_io_stall_seconds{operation=\"write\",type=\"LOG\",job=~\"$job\",db=~\"$db\"}[$interval])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database latency Read (ROWS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_io_stall_seconds{operation=\"read\",type=\"ROWS\",job=~\"$job\",db=~\"$db\"}[$interval])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Database latency Write (ROWS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_io_stall_seconds{operation=\"write\",type=\"ROWS\",job=~\"$job\",db=~\"$db\"}[$interval])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mssql_transactions_total{job=\"$job\"}[$interval])",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_buffer_cache_hit_ratio{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Space used by DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (db)(mssql_disk_space_used_database_bytes_total{job=~\"$job\",db=~\"$db\"})",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Space used by table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_table_used_size_bytes_total{job=~\"$job\",db=~\"$db\"}",
     "legendFormat": "{{db}} > {{obj_name}}"
    }
   ]
  }
 ]
}