{
 "title": "Postgresql - Instance Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(pg_up,instance)" }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pg_up{instance='$instance'}" }
   ]
  },
  {
   "title": "Postmaster Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "time() - pg_postmaster_start_time_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "DBs Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance='$instance'}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Scheduled vs Requested Checkpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_req{instance='$instance'}[5m])",
     "legendFormat": "requested"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_timed{instance='$instance'}[5m])",
     "legendFormat": "scheduled"
    }
   ]
  },
  {
   "title": "WAL Files Archive Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(pg_stat_archiver_failed_count{instance='$instance'}[5m]) / (rate(pg_stat_archiver_archived_count{instance='$instance'}[5m]) + rate(pg_stat_archiver_failed_count{instance='$instance'}[5m]))",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Checkpoint time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{instance='$instance'}[5m])",
     "legendFormat": "synchronizing to disk"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{instance='$instance'}[5m])",
     "legendFormat": "writting to disk"
    }
   ]
  },
  {
   "title": "Backend Buffer Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(pg_stat_bgwriter_buffers_backend{instance='$instance'}[5m])/  (rate(pg_stat_bgwriter_buffers_backend{instance='$instance'}[5m]) + rate(pg_stat_bgwriter_buffers_checkpoint{instance='$instance'}[5m]) + rate(pg_stat_bgwriter_buffers_clean{instance='$instance'}[5m]))",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Buffers Allocated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{instance='$instance'}[5m])",
     "legendFormat": "buffers"
    }
   ]
  },
  {
   "title": "Background Writer Stops for Max Write Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_maxwritten_clean{instance='$instance'}[5m])",
     "legendFormat": "stops"
    }
   ]
  },
  {
   "title": "Connections Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(pg_stat_activity_count{instance='$instance'}) by (instance)  / ((sum(pg_settings_max_connections{instance='$instance'}) by (instance)) - sum(pg_settings_superuser_reserved_connections{instance='$instance'}) by (instance))",
     "legendFormat": "Connections usage"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "((sum(pg_settings_max_connections{instance='$instance'}) by (instance)) - sum(pg_settings_superuser_reserved_connections{instance='$instance'}) by (instance)) - sum(pg_stat_activity_count{instance='$instance'}) by (instance) ",
     "legendFormat": "Available Conns"
    }
   ]
  },
  {
   "title": "Max Transaction Time by DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(pg_stat_activity_max_tx_duration{instance='$instance',datname!~\"template.*\"}[5m])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}