{
 "title": "HAProxy Proxy Golden Signals",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "proxy",
    "query": "label_values(haproxy_backend_sessions_total,proxy)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(haproxy_backend_status{proxy='$proxy'}==1 or vector(0))"
    }
   ]
  },
  {
   "title": "Instances Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(haproxy_backend_status{proxy='$proxy'}==0 or vector(0))"
    }
   ]
  },
  {
   "title": "Sessions Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * max(rate(haproxy_backend_sessions_total{proxy='$proxy'}[$__interval]) / haproxy_backend_limit_sessions{proxy='$proxy'})",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Queued Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(haproxy_backend_current_queue{proxy='$proxy'})",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(haproxy_backend_http_responses_total{code!=\"2xx\",proxy='$proxy'}[$__interval])) / sum(rate(haproxy_backend_http_responses_total{proxy='$proxy'}[$__interval])) ",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Denial Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_requests_denied_total{proxy=\"$proxy\"}[$__interval])) / sum(rate(haproxy_backend_http_requests_total{proxy=\"$proxy\"}[$__interval]))",
     "legendFormat": "Requets"
    },
    {
     "expr": "sum(rate(haproxy_backend_responses_denied_total{proxy=\"$proxy\"}[$__interval])) / sum(rate(haproxy_backend_http_responses_total{proxy=\"$proxy\"}[$__interval]))",
     "legendFormat": "Responses"
    }
   ]
  },
  {
   "title": "HTTP Error by Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{code!=\"2xx\",proxy='$proxy'}[$__interval])) ",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Data Transfers Aborted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_client_aborts_total{proxy=\"$proxy\"}[$__interval])) ",
     "legendFormat": "By Client"
    },
    {
     "expr": "sum(rate(haproxy_backend_server_aborts_total{proxy=\"$proxy\"}[$__interval])) ",
     "legendFormat": "By Server"
    }
   ]
  },
  {
   "title": "Mean Response Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(haproxy_backend_response_time_average_seconds{proxy=\"$proxy\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean Connect and Queue Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(haproxy_backend_queue_time_average_seconds{proxy=\"$proxy\"})",
     "legendFormat": "Queue Time"
    },
    {
     "expr": "max(haproxy_backend_connect_time_average_seconds{proxy=\"$proxy\"})",
     "legendFormat": "Connect Time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{proxy=\"$proxy\"}[$__interval]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{proxy=\"$proxy\"}[$__interval]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=\"$proxy\"}[$__interval]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Request and Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{proxy=\"$proxy\"}[$__interval])) / sum(rate(haproxy_backend_http_requests_total{proxy=\"$proxy\"}[$__interval])) ",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{proxy=\"$proxy\"}[$__interval])) / sum(rate(haproxy_backend_http_responses_total{proxy=\"$proxy\"}[$__interval])) ",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}