groups:
    - name: Memcached
      rules:
        - alert: '[Memcached] Instance Down'
          expr: |
            memcached_up == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            description: Instance is not reachable
        - alert: '[Memcached] Low UpTime'
          expr: |
            memcached_uptime_seconds < 3600
          for: 5m
          labels:
            severity: critical
          annotations:
            description: Uptime of less than 1 hour in a Memcached instance
        - alert: '[Memcached] Connection Throttled'
          expr: |
            rate(memcached_connections_yielded_total[5m]) > 5
          for: 10m
          labels:
            severity: critical
          annotations:
            description: Connection throttled because max number of requests per event process reached
        - alert: '[Memcached] Connections Close To The Limit 85%'
          expr: |
            memcached_current_connections/ memcached_max_connections > 0.85
          for: 5m
          labels:
            severity: warning
          annotations:
            description: The mumber of connections are close to the limit
        - alert: '[Memcached] Connections Limit Reached'
          expr: |
            rate(memcached_connections_listener_disabled_total[5m]) > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            description: Reached the number of maximum connections and caused a connection error
