apiVersion: v1
kind: Alert
app: "postgresql"
version: 1.0.0
appVersion:
- "12"
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: PostgreSQL
      rules:
      - alert: InstanceDown
        expr: pg_up == 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Instance down {{$labels.instance}}
      - alert: LowUpTime
        expr: time() - pg_postmaster_start_time_seconds < 3600
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Low uptime of postmaster in instance {{$labels.instance}}
      - alert: MaxWriteBufferReached
        expr: rate(pg_stat_bgwriter_maxwritten_clean[5m]) > 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Background writer stops for max. write buffers reached in instance {{$labels.instance}}
      - alert: HighWALFilesArchiveErrorRate
        expr: |
          rate(pg_stat_archiver_failed_count[5m]) /
          (rate(pg_stat_archiver_archived_count[5m]) +
            rate(pg_stat_archiver_failed_count[5m])) > 0.1
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High error rate in WAL files archiver in instance {{$labels.instance}}
      - alert: LowAvailableConnections
        expr: |
          sum(pg_stat_activity_count) by (instance)  /
          ((sum(pg_settings_max_connections) by (instance)) -
            sum(pg_settings_superuser_reserved_connections) by (instance)) > 0.85
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Low available connections in instance {{$labels.instance}}
      - alert: HighResponseTime
        expr: |
          avg(rate(pg_stat_activity_max_tx_duration{datname!~"template.*"}[5m])) by (datname) > 2 * 60
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High response time in database {{$labels.datname}}
      - alert: LowCacheHitRate
        expr: |
          avg(rate(pg_stat_database_blks_hit{datname!~"template.*"}[5m]) /
          (rate(pg_stat_database_blks_hit{datname!~"template.*"}[5m]) +
            rate(pg_stat_database_blks_read{datname!~"template.*"}[5m]))) < 0.9
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Low cache hit rate in database {{$labels.datname}}
      - alert: DeadLocksInDatabase
        expr: |
          rate(pg_stat_database_deadlocks{datname!~"template.*"}[5m]) > 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Deadlocks in database {{$labels.datname}}
