{
 "title": "Portworx Cluster",
 "description": "Portworx Cluster",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Healthy Nodes Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_node_status_node_status == 2",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Nodes Error Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_node_status_node_status != 2",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "KVDB Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_kvdb_health_state_node_view == 1",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "px_kvdb_health_state_node_view == 2",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(px_network_io_sent_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(px_network_io_received_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cluster Storage Space per Node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_cluster_disk_available_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Node % Available Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_cluster_disk_available_bytes / px_cluster_disk_total_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_disk_stats_used_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Disk Read / Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(px_disk_stats_num_reads_total[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(px_disk_stats_num_writes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk Read / Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(px_disk_stats_read_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(px_disk_stats_written_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk Read / Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_disk_stats_read_latency_seconds",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "px_disk_stats_write_latency_seconds",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cluster Storage Space per Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_pool_stats_available_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Pool Flush / Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(px_pool_stats_flushed_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    },
    { "expr": "px_pool_stats_written_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Pool Status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_pool_stats_status == 0", "legendFormat": "{{ handler }}" },
    { "expr": "px_pool_stats_status == 1", "legendFormat": "{{ handler }}" },
    { "expr": "px_pool_stats_status == 2", "legendFormat": "{{ handler }}" },
    { "expr": "px_pool_stats_status == 3", "legendFormat": "{{ handler }}" },
    { "expr": "px_pool_stats_status == 4", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Pool Flush / Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(px_pool_stats_num_flushes_total[5m])",
     "legendFormat": "{{ handler }}"
    },
    { "expr": "px_pool_stats_num_writes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Pool Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_pool_stats_write_latency_seconds",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_px_cache_read_hits / ( px_px_cache_read_hits +  px_px_cache_read_miss )",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Pool % Available Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_pool_stats_available_bytes / px_pool_stats_total_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(px_cluster_status_quorum != 1) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "max(px_cluster_status_size)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Nodes online",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(px_cluster_status_nodes_online)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Nodes offline",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(px_cluster_status_nodes_offline)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Nodes storage down",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(px_cluster_status_nodes_storage_down)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Storage nodes online",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Storage nodes offline",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(px_cluster_status_storage_nodes_offline)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Storage Nodes Decommissioned",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_decommissioned)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "License expiration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(px_node_status_license_expiry)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "KVDB Healthy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(px_kvdb_health_state_node_view == 1) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "KVDB Unhealthy ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(px_kvdb_health_state_node_view == 2) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Cluster Health", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Cluster Health" } },
  { "title": "Disk Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 }, "options": { "content": "# Disk Stats" } },
  { "title": "Pool Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 }, "options": { "content": "# Pool Stats" } },
  { "title": "Cache Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 }, "options": { "content": "# Cache Stats" } }
 ]
}