{
 "title": "Portworx Volumes",
 "description": "Portworx Volumes",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Volume State Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_volume_state == 0", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 1", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 2", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 3", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 4", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 5", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 6", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 7", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 8", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_state == 9", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Volume Attached State Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_volume_attached_state == 0", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_attached_state == 1", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_attached_state == 2", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Volume Status Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_volume_status == 0", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_status == 1", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_status == 2", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_status == 3", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_status == 4", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_volume_capacity_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_volume_usage_bytes/px_volume_capacity_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Volume HA Level",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_volume_halevel", "legendFormat": "{{ handler }}" },
    { "expr": "px_volume_currhalevel", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Volume Replication Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "px_volume_replication_status == 0",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "px_volume_replication_status == 1",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "px_volume_replication_status == 2",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "px_volume_replication_status == 3",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "px_volume_replication_status == 4",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "px_volume_replication_status == 5",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Volume Read / Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(px_volume_reads_total[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(px_volume_writes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Volume Read / Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(px_volume_read_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(px_volume_written_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Volume Read / Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "px_volume_read_latency_seconds", "legendFormat": "{{ handler }}" },
    {
     "expr": "px_volume_write_latency_seconds",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Volumes attached\n",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(px_volume_attached == 1) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Volumes detached",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(px_volume_attached == 0) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}