{
 "title": "MongoDB - Database details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(mongodb_up,instance)"
   },
   {
    "name": "db",
    "query": "label_values(mongodb_mongod_db_collections_total,db)"
   }
  ]
 },
 "panels": [
  {
   "title": "Data Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_mongod_db_data_size_bytes{instance='$instance',db='$db'} ",
     "legendFormat": "data"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_mongod_db_index_size_bytes{instance='$instance',db='$db'} ",
     "legendFormat": "index"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_mongod_db_objects_total{instance='$instance',db='$db'} ",
     "legendFormat": "data"
    }
   ]
  },
  {
   "title": "Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_mongod_db_indexes_total{instance='$instance',db='$db'} ",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_mongod_db_collections_total{instance='$instance',db='$db'} "
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_db_data_size_bytes{instance='$instance',db='$db'} ",
     "legendFormat": "data"
    },
    {
     "expr": "mongodb_mongod_db_index_size_bytes{instance='$instance',db='$db'} ",
     "legendFormat": "index"
    }
   ]
  },
  {
   "title": "Objects and Indexes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_db_indexes_total{instance='$instance',db='$db'} ",
     "legendFormat": "Index"
    },
    {
     "expr": "mongodb_mongod_db_objects_total{instance='$instance',db='$db'} ",
     "legendFormat": "Object"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_db_collections_total{instance='$instance',db='$db'} ",
     "legendFormat": "Collections"
    }
   ]
  }
 ]
}