{
 "title": "MongoDB - Instance Health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(mongodb_up,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_up{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Asserts (errors)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_asserts_total{instance='$instance'}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory page faults",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_extra_info_page_faults_total{instance='$instance'}[5m])",
     "legendFormat": "Page faults"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "DBs Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_db_data_size_bytes{instance='$instance'} + mongodb_mongod_db_index_size_bytes{instance='$instance'} ",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{instance='$instance'}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{instance='$instance'}[5m]) / rate(mongodb_mongod_op_latencies_ops_total{instance='$instance'}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Lock Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance='$instance'}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Lock Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_client{instance='$instance'}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Global Lock Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100 * mongodb_mongod_global_lock_ratio{instance='$instance'}",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Tickets Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{instance='$instance'} / mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{instance='$instance'})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cursors Opened",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_cursor_open{instance='$instance',state!=\"total\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cursors Timed Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_cursor_timed_out_total{instance='$instance'}[5m])",
     "legendFormat": "Cursors"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_connections_metrics_created_total{instance='$instance'}[5m])",
     "legendFormat": "Conns"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance='$instance'}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_metrics_num_requests_total{instance='$instance'}[5m])",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance='$instance'}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance='$instance',type!=\"total\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance='$instance'}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Dirty Pages Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(mongodb_mongod_wiredtiger_cache_pages{instance='$instance',type=\"dirty\"}) / sum(mongodb_mongod_wiredtiger_cache_pages{instance='$instance',type=\"total\"})",
     "legendFormat": "Dirty rate"
    }
   ]
  },
  {
   "title": "Cache Evicted Pages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}