groups:
    - name: MongoDB
      rules:
        - alert: '[MongoDB] Instance Down'
          expr: |
            mongodb_up != 1
          for: 10m
          labels:
            severity: critical
          annotations:
            description: Mongo server detected down by instance
        - alert: '[MongoDB] Uptime less than one hour'
          expr: |
            mongodb_instance_uptime_seconds < 3600
          for: 10m
          labels:
            severity: critical
          annotations:
            description: Mongo server detected down by instance
        - alert: '[MongoDB] Asserts detected'
          expr: |
            rate(mongodb_asserts_total{type=~"regular|user|message"}[5m]) < 3600
          for: 10m
          labels:
            severity: critical
          annotations:
            description: Mongo server detected down by instance
        - alert: '[MongoDB] High Latency'
          expr: |
            rate(mongodb_mongod_op_latencies_latency_total[5m]) / rate(mongodb_mongod_op_latencies_ops_total[5m]) > 250000
          for: 10m
          labels:
            severity: critical
          annotations:
            description: High latency in instance
        - alert: '[MongoDB] High Ticket Utilization'
          expr: |
            (mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets / mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets)> 0.75
          for: 10m
          labels:
            severity: critical
          annotations:
            description: Ticket usage over 75% in instance
        - alert: '[MongoDB] Recurrent Cursor Timeout'
          expr: |
            rate(mongodb_mongod_metrics_cursor_timed_out_total[5m]) > 0
          for: 30m
          labels:
            severity: critical
          annotations:
            description: Recurrent cursors timeout in instance
        - alert: '[MongoDB] Recurrent Memory Page Faults'
          expr: |
            rate(mongodb_extra_info_page_faults_total[5m]) > 0
          for: 30m
          labels:
            severity: critical
          annotations:
            description: Recurrent cursors timeout in instance
