{
 "title": "Nginx_Kubernetes_Ingress_Controller",
 "description": "Nginx_Kubernetes_Ingress_Controller",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum by (ingress)(irate(nginx_ingress_controller_requests{status=~\"2..|3..\"}[5m])), 0.001)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (nginx_ingress_controller_nginx_process_connections)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Controller Error Rate (~4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (ingress)(rate(nginx_ingress_controller_requests{status=~\"[4-5].*\"}[5m])) / sum by (ingress)(rate(nginx_ingress_controller_requests[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(ingress) (irate (nginx_ingress_controller_request_size_sum[5m]))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum by(ingress) (irate (nginx_ingress_controller_response_size_sum[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg (nginx_ingress_controller_nginx_process_resident_memory_bytes) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds) by (host) - time()",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (ingress)(rate(nginx_ingress_controller_ingress_upstream_latency_seconds_sum[5m])) / sum by (ingress)(rate(nginx_ingress_controller_ingress_upstream_latency_seconds_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (ingress)(rate(nginx_ingress_controller_request_duration_seconds_sum{status=~\"2..|3..\"}[5m])) /sum by (ingress)(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"2..|3..\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (ingress)(rate(nginx_ingress_controller_response_duration_seconds_sum{status=~\"2..|3..\"}[5m])) / sum by (ingress)(rate(nginx_ingress_controller_response_duration_seconds_count{status=~\"2..|3..\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Config Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_config_last_reload_successful==0) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Last OK Config Reload",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "time() - max(nginx_ingress_controller_config_last_reload_successful_timestamp_seconds)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Errors", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "### Errors" } },
  { "title": "Errors (2)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 }, "options": { "content": "### Latency and Response Time" } },
  { "title": "Errors (3)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 }, "options": { "content": "### Traffic and Connections" } },
  { "title": "Errors (4)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 }, "options": { "content": "### CPU & Memory" } },
  { "title": "Errors (5)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 }, "options": { "content": "### Certificates Expiration" } }
 ]
}