{
 "title": "Ocp4 / API server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(apiserver_request_total, cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(apiserver_request_total{job=\"apiserver\", cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up:kubernetes{job=\"apiserver\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total:kubernetes_apiservers{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total:kubernetes_apiservers{code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total:kubernetes_apiservers{code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total:kubernetes_apiservers{code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "apiserver_request_duration_seconds_bucket:kubernetes_apiservers{verb!=\"WATCH\"}",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total:kubernetes_apiservers[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth:kubernetes_apiservers[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workqueue_queue_duration_seconds_bucket:kubernetes_apiservers",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Entry Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_helper_cache_entry_total:kubernetes_apiservers[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Hit/Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_helper_cache_hit_total:kubernetes_apiservers[5m])) by (instance)",
     "legendFormat": "{{instance}} hit"
    },
    {
     "expr": "sum(rate(etcd_helper_cache_miss_total:kubernetes_apiservers[5m])) by (instance)",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "ETCD Cache Duration 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "etcd_request_cache_get_duration_seconds_bucket:kubernetes_apiservers",
     "legendFormat": "{{instance}} get"
    },
    {
     "expr": "etcd_request_cache_add_duration_seconds_bucket:kubernetes_apiservers",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes:kubernetes{job=\"apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total:kubernetes{job=\"apiserver\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines:kubernetes{job=\"apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "oc4 / Controller Manager",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(up:kubernetes{job=\"kubernetes-nodes\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up:controllermanager{job=\"kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total:kubernetes_control_manager{job=\"kube-controller-manager\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth:kubernetes_control_manager{job=\"kube-controller-manager\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workqueue_queue_duration_seconds_bucket:kubernetes_apiservers",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total:kubernetes_control_manager{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kubernetes_control_manager{code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kubernetes_control_manager{code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kubernetes_control_manager{code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rest_client_request_latency_seconds_bucket:kubernetes_control_manager:post",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rest_client_request_latency_seconds_bucket:kubernetes_control_manager:get",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes:kubernetes{job=\"controller-manager\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up:controllermanager{job=\"kube-controller-manager\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines:kubernetes{job=\"controller-manager\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "oc4 / Kubelet",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(kubelet_runtime_operations_total{cluster=\"$cluster\", job=\"kubelet\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up:kubernetes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count:kubelet)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Container",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count:kubelet)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Actual Volume Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes:kubelet{state=\"actual_state_of_world\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Desired Volume Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes:desired:kubelet{job=\"kubelet\",state=\"desired_state_of_world\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Config Error Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(rate(kubelet_node_config_error:kubelet[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_total:kubelet[5m])) by (operation_type, instance)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total:kubelet[5m])) by (instance, operation_type)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "operation_duration_seconds:kubelet",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Pod Start Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_pod_start_duration_seconds_count:kubelet[5m])) by (instance)",
     "legendFormat": "{{instance}} pod"
    },
    {
     "expr": "sum(rate(kubelet_pod_worker_duration_seconds_count:kubelet[5m])) by (instance)",
     "legendFormat": "{{instance}} worker"
    }
   ]
  },
  {
   "title": "Pod Start Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pod_start_duration_seconds:kubelet",
     "legendFormat": "{{instance}} pod"
    },
    {
     "expr": "pod_worker_duration_seconds:kubelet",
     "legendFormat": "{{instance}} worker"
    }
   ]
  },
  {
   "title": "Storage Operation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_duration_seconds_count:kubelet[5m])) by (instance, operation_name, volume_plugin)",
     "legendFormat": "{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_errors_total:kubelet[5m])) by (instance, operation_name, volume_plugin)",
     "legendFormat": "{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "storage_operation_duration_seconds:kubelet",
     "legendFormat": "{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Cgroup manager operation rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_cgroup_manager_duration_seconds_count:kubelet[5m])) by (instance, operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Cgroup manager 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cgroup_manager_duration_seconds:kubelet",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "PLEG relist rate",
   "type": "graph",
   "description": "Pod lifecycle event generator",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pleg_relist_duration_seconds:kubelet[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PLEG relist interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pleg_relist_interval_seconds:kubelet",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PLEG relist duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pleg_relist_duration_seconds:kubelet",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total_code:kubelet{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total_code:kubelet{code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total_code:kubelet{code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total_code:kubelet{code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "request_duration_seconds:kubelet",
     "legendFormat": "{{instance}} {{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes:kubernetes{job=\"kubelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total:kubernetes{job=\"kubelet\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines:kubernetes{job=\"kubelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Oc4 / Scheduler",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(kubelet_running_pod_count:kubernetes_nodes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    { "expr": "sum(up:kube_scheduler)" }
   ]
  },
  {
   "title": "Scheduling Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scheduler_e2e_scheduling_duration_seconds_count:kube_scheduler[5m])) by (instance)",
     "legendFormat": "{{instance}} e2e"
    },
    {
     "expr": "sum(rate(scheduler_binding_duration_seconds_count:kube_scheduler[5m])) by (instance)",
     "legendFormat": "{{instance}} binding"
    },
    {
     "expr": "sum(rate(scheduler_scheduling_algorithm_duration_seconds_count:kube_scheduler[5m])) by (instance)",
     "legendFormat": "{{instance}} scheduling algorithm"
    },
    {
     "expr": "sum(rate(scheduler_volume_scheduling_duration_seconds_count:kube_scheduler[5m])) by (instance)",
     "legendFormat": "{{instance}} volume"
    }
   ]
  },
  {
   "title": "Scheduling latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scheduler_volume_scheduling_duration_seconds_count:kube_scheduler",
     "legendFormat": "{{instance}} e2e"
    },
    {
     "expr": "scheduler_binding_duration_seconds_bucket:kube_scheduler",
     "legendFormat": "{{instance}} binding"
    },
    {
     "expr": "scheduler_scheduling_algorithm_duration_seconds_bucket:kube_scheduler",
     "legendFormat": "{{instance}} scheduling algorithm"
    },
    {
     "expr": "scheduler_volume_scheduling_duration_seconds_bucket:kube_scheduler",
     "legendFormat": "{{instance}} volume"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total:kube_scheduler{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kube_scheduler{code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kube_scheduler{code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kube_scheduler{code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rest_client_request_latency_seconds_bucket:kube_scheduler{verb=\"POST\"}",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rest_client_request_latency_seconds_bucket:kube_scheduler{verb=\"GET\"}",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes:kubernetes{job=\"scheduler\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total:kubernetes{job=\"scheduler\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines:kubernetes{job=\"scheduler\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}