groups:
    - name: Windows
      rules:
        - alert: '[Windows] High CPU Usage'
          expr: |
            100 * sum by (instance) (rate(windows_cpu_time_total{ mode != 'idle'}[5m])) / count by (instance) (windows_cpu_core_frequency_mhz) > 95
          for: 5m
          labels:
            severity: info
          annotations:
            description: The CPU of the Windows instance reached 95% of use
        - alert: '[Windows] High Disk Usage'
          expr: |
            100 * (windows_logical_disk_size_bytes - windows_logical_disk_free_bytes) / windows_logical_disk_size_bytes > 95
          for: 5m
          labels:
            severity: critical
          annotations:
            description: Disk full over 95% in instance {{$labels.instance}}
        - alert: '[Windows] High Physical Memory Usage'
          expr: |
            100 * (windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes) / windows_cs_physical_memory_bytes > 95
          for: 5m
          labels:
            severity: critical
          annotations:
            description: High physical memory usage in instance
        - alert: '[Windows] High Network Inbound Errors'
          expr: |
            100 * rate(windows_net_packets_received_errors[5m]) / (rate(windows_net_packets_received_errors[5m]) + rate(windows_net_packets_received_total[5m])>0) > 75
          for: 5m
          labels:
            severity: critical
          annotations:
            description: High inbound network error rate in instance
        - alert: '[Windows] High Network Outbound Errors'
          expr: |
            100 * rate(windows_net_packets_outbound_errors[5m]) / (rate(windows_net_packets_outbound_errors[5m]) + rate(windows_net_packets_sent_total[5m])>0) > 75
          for: 5m
          labels:
            severity: critical
          annotations:
            description: High outbound network error rate in instance
        - alert: '[Windows] Increase of Disk writes time'
          expr: |
            rate(windows_logical_disk_write_seconds_total[5m]) / rate(windows_logical_disk_writes_total[5m]) > 0.01
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Increase of Disk writes time
        - alert: '[Windows] Queue of Writes and reads Disk operations is growing'
          expr: |
            windows_logical_disk_requests_queued > 10
          for: 5m
          labels:
            severity: critical
          annotations:
            description: The queue for writes and reads disk operations is growing
        - alert: '[Windows] High percent of swap space used'
          expr: |
            (windows_os_virtual_memory_bytes - windows_os_virtual_memory_free_bytes) / windows_os_virtual_memory_bytes > 0.8
          for: 5m
          labels:
            severity: critical
          annotations:
            description: The swap space has reached high amount of used
        - alert: '[Windows] Network bandwidth is reaching its limit'
          expr: |
            (rate(windows_net_bytes_total[5m])/windows_net_current_bandwidth_bytes) > 0.8
          for: 5m
          labels:
            severity: critical
          annotations:
            description: Network Bandwith use is reaching its limit
        - alert: '[Windows] High number of transitions virtual addresses into disk'
          expr: |
            rate(windows_memory_transition_faults_total[5m]) > 800
          for: 5m
          labels:
            severity: critical
          annotations:
            description: The rate at which pages transition to resident memory without being written to disk has reached problematic limit
