{
 "title": "CoreDNS",
 "tags": [ "coredns-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(coredns_dns_response_rcode_count_total:sysdig{job=\"coredns-monitoring\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up:kubernetes{job=\"coredns-monitoring\"})"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(coredns_panic_count_total:sysdig{job=\"coredns-monitoring\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "sum(rate(coredns_forward_response_rcode_count_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "forward {{rcode}}"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (server, zone, le))",
     "legendFormat": "{{server}} {{zone}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (to, le))",
     "legendFormat": "forward {{to}}"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Forward Requests (by to)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_request_count_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(coredns_cache_hits_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}) / (sum(coredns_cache_misses_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}) + sum(coredns_cache_hits_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Cache hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_cache_size:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Plugins Enabled",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "count(sum(coredns_plugin_enabled:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}) by (name))"
    }
   ]
  },
  {
   "title": "Request size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (server, zone, proto, le))",
     "legendFormat": "99th {{server}} {{zone}} {{proto}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (server, zone, proto, le))",
     "legendFormat": "50th {{server}} {{zone}} {{proto}}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (server, zone, proto, le))",
     "legendFormat": "99th {{server}} {{zone}} {{proto}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket:sysdig{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])) by (server, zone, proto, le))",
     "legendFormat": "50th {{server}} {{zone}} {{proto}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes:kubernetes{job=\"coredns-monitoring\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total:kubernetes{job=\"coredns-monitoring\",pod=~\"$instance\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines:kubernetes{job=\"coredns-monitoring\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}