apiVersion: v1
kind: Alert
app: AWS ELB
version: 1.0.0
appVersion:
- 1.0.0
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: AWS-ELB
      rules:
      - alert: High4XXErrorsFromLoadBalancer
        expr: |
          aws_elb_httpcode_elb_4_xx_count_sum / aws_elb_request_count_sum
          > 0.15
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High 4XX error rate in load balancer {{$labels.dimension_LoadBalancerName}}
      - alert: High5XXErrorsFromLoadBalancer
        expr: |
          aws_elb_httpcode_elb_5_xx_count_sum / aws_elb_request_count_sum
          > 0.15
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High 5XX error rate in load balancer {{$labels.dimension_LoadBalancerName}}
      - alert: High4XXErrorsFromBackend
        expr: |
          aws_elb_httpcode_backend_4_xx_count_sum / aws_elb_request_count_sum
          > 0.15
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High 4XX error rate in load balancer {{$labels.dimension_LoadBalancerName}}
      - alert: High5XXErrorsFromBackend
        expr: |
          aws_elb_httpcode_backend_5_xx_count_sum / aws_elb_request_count_sum
          > 0.15
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High 5XX error rate in load balancer {{$labels.dimension_LoadBalancerName}}
      - alert: UnhealthyHostInLoadBalancer
        expr: aws_elb_un_healthy_host_count_minimum > 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Unhealthy host detected in load balancer {{$labels.dimension_LoadBalancerName}}
      - alert: QueueSpilloverRejections
        expr: aws_elb_spillover_count_sum > 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Recurrent queue spillover rejections in load balancer {{$labels.dimension_LoadBalancerName}}
      - alert: HighLatencyInLoadBalancer
        expr: aws_elb_latency_p95 > 0.250
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High latency in load balancer {{$labels.dimension_LoadBalancerName}}
