{
 "title": "OpenShift_HAProxy_Ingress_Service_Details",
 "description": "OpenShift_HAProxy_Ingress_Service_Details",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average response latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "haproxy_server_http_average_response_latency_milliseconds",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Downtime By Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_downtime_seconds_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "HTTP Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(haproxy_server_http_responses_total[5m])) / sum (rate(haproxy_server_http_responses_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Bytes Inbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_bytes_in_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Bytes Outbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_bytes_out_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Check Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by ( service)(rate(haproxy_server_check_failures_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Connection Errors by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_connection_errors_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_connections_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Responses OK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_http_responses_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "New Panel", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "### Health & Errors" } },
  { "title": "New Panel (2)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 }, "options": { "content": "### Latency & Queue" } },
  { "title": "New Panel (3)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 }, "options": { "content": "### Traffic & Connections" } }
 ]
}