repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
releases:
  - name: prometheus-controlplane
    namespace: monitoring
    chart: stable/prometheus
    atomic: true
    values:
      - prometheus.yml.gotmpl
