- "alert": "KubePodCrashLooping"
  "annotations":
    "message": "Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf \"%.2f\" $value }} times / 5 minutes."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping"
  "expr": |
    rate(kube_pod_container_status_restarts_total:sysdig{job="kubernetes-service-endpoints"}[5m]) * 60 * 5 > 0
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubePodNotReady"
  "annotations":
    "message": "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready"
  "expr": |
    sum by (namespace, pod) (
      max by(namespace, pod) (
        kube_pod_status_phase:sysdig{job="kubernetes-service-endpoints", phase=~"Pending|Unknown"}
      ) * on(namespace, pod) group_left(owner_kind) topk by(namespace, pod) (
        1, max by(namespace, pod, owner_kind) (kube_pod_owner:sysdig{owner_kind!="Job"})
      )
    ) > 0
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeDeploymentGenerationMismatch"
  "annotations":
    "message": "Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} does not match, this indicates that the Deployment has failed but has not been rolled back."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch"
  "expr": |
    kube_deployment_status_observed_generation:sysdig{job="kubernetes-service-endpoints"}
      !=
    kube_deployment_metadata_generation:sysdig{job="kubernetes-service-endpoints"}
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeDeploymentReplicasMismatch"
  "annotations":
    "message": "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas for longer than 15 minutes."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentreplicasmismatch"
  "expr": |
    (
      kube_workload_status_desired:sysdig{job="kubernetes-service-endpoints",workload_type="deployment"}
        !=
      kube_workload_status_available:sysdig{job="kubernetes-service-endpoints",workload_type="deployment"}
    ) and (
      changes(kube_workload_status_updated:sysdig{job="kubernetes-service-endpoints",workload_type="deployment"}[5m])
        ==
      0
    )
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeStatefulSetReplicasMismatch"
  "annotations":
    "message": "StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} has not matched the expected number of replicas for longer than 15 minutes."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetreplicasmismatch"
  "expr": |
    (
      kube_workload_status_desired:sysdig{job="kubernetes-service-endpoints",workload_type="statefulset"}
        !=
      kube_workload_status_available:sysdig{job="kubernetes-service-endpoints",workload_type="statefulset"}
    ) and (
      changes(kube_workload_status_updated:sysdig{job="kubernetes-service-endpoints",workload_type="statefulset"}[5m])
        ==
      0
    )
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeStatefulSetGenerationMismatch"
  "annotations":
    "message": "StatefulSet generation for {{ $labels.namespace }}/{{ $labels.statefulset }} does not match, this indicates that the StatefulSet has failed but has not been rolled back."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetgenerationmismatch"
  "expr": |
    kube_statefulset_status_observed_generation:sysdig{job="kubernetes-service-endpoints"}
      !=
    kube_statefulset_metadata_generation:sysdig{job="kubernetes-service-endpoints"}
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeStatefulSetUpdateNotRolledOut"
  "annotations":
    "message": "StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} update has not been rolled out."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetupdatenotrolledout"
  "expr": |
    (
      max without (revision) (
        kube_statefulset_status_current_revision:sysdig{job="kubernetes-service-endpoints"}
          unless
        kube_statefulset_status_update_revision:sysdig{job="kubernetes-service-endpoints"}
      )
        *
      (
        kube_statefulset_replicas:sysdig{job="kubernetes-service-endpoints"}
          !=
        kube_workload_status_updated:sysdig{job="kubernetes-service-endpoints",workload_type="statefulset"}
      )
    )  and (
      changes(kube_workload_status_updated:sysdig{job="kubernetes-service-endpoints",workload_type="statefulset"}[5m])
        ==
      0
    )
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeDaemonSetRolloutStuck"
  "annotations":
    "message": "Only {{ $value | humanizePercentage }} of the desired Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are scheduled and ready."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck"
  "expr": |
    kube_daemonset_status_number_ready:sysdig{job="kubernetes-service-endpoints"}
      /
    kube_daemonset_status_desired_number_scheduled:sysdig{job="kubernetes-service-endpoints"} < 1.00
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeContainerWaiting"
  "annotations":
    "message": "Pod {{ $labels.namespace }}/{{ $labels.pod }} container {{ $labels.container}} has been in waiting state for longer than 1 hour."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontainerwaiting"
  "expr": |
    sum by (namespace, pod, container) (kube_pod_container_status_waiting_reason:sysdig{job="kubernetes-service-endpoints"}) > 0
  "for": "1h"
  "labels":
    "severity": "warning"
- "alert": "KubeDaemonSetNotScheduled"
  "annotations":
    "message": "{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are not scheduled."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetnotscheduled"
  "expr": |
    kube_daemonset_status_desired_number_scheduled:sysdig{job="kubernetes-service-endpoints"}
      -
    kube_daemonset_status_current_number_scheduled:sysdig{job="kubernetes-service-endpoints"} > 0
  "for": "10m"
  "labels":
    "severity": "warning"
- "alert": "KubeDaemonSetMisScheduled"
  "annotations":
    "message": "{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are running where they are not supposed to run."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetmisscheduled"
  "expr": |
    kube_daemonset_status_number_misscheduled:sysdig{job="kubernetes-service-endpoints"} > 0
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeJobCompletion"
  "annotations":
    "message": "Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than one hour to complete."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobcompletion"
  "expr": |
    kube_job_spec_completions:sysdig{job="kubernetes-service-endpoints"} - kube_job_status_succeeded:sysdig{job="kubernetes-service-endpoints"}  > 0
  "for": "1h"
  "labels":
    "severity": "warning"
- "alert": "KubeJobFailed"
  "annotations":
    "message": "Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobfailed"
  "expr": |
    kube_job_failed:sysdig{job="kubernetes-service-endpoints"}  > 0
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeCPUOvercommit"
  "annotations":
    "message": "Cluster has overcommitted CPU resource requests for Pods and cannot tolerate node failure."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuovercommit"
  "expr": |
    sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum{})
      /
    sum(kube_node_status_allocatable_cpu_cores:sysdig)
      >
    (count(kube_node_status_allocatable_cpu_cores:sysdig)-1) / count(kube_node_status_allocatable_cpu_cores:sysdig)
  "for": "5m"
  "labels":
    "severity": "warning"
- "alert": "KubeMemoryOvercommit"
  "annotations":
    "message": "Cluster has overcommitted memory resource requests for Pods and cannot tolerate node failure."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubememoryovercommit"
  "expr": |
    sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum{})
      /
    sum(kube_node_status_allocatable_memory_bytes:sysdig)
      >
    (count(kube_node_status_allocatable_memory_bytes:sysdig)-1)
      /
    count(kube_node_status_allocatable_memory_bytes:sysdig)
  "for": "5m"
  "labels":
    "severity": "warning"
- "alert": "KubeCPUQuotaOvercommit"
  "annotations":
    "message": "Cluster has overcommitted CPU resource requests for Namespaces."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuquotaovercommit"
  "expr": |
    sum(kube_resourcequota:sysdig{job="kubernetes-service-endpoints", type="hard", resource="cpu"})
      /
    sum(kube_node_status_allocatable_cpu_cores:sysdig)
      > 1.5
  "for": "5m"
  "labels":
    "severity": "warning"
- "alert": "KubeMemoryQuotaOvercommit"
  "annotations":
    "message": "Cluster has overcommitted memory resource requests for Namespaces."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubememoryquotaovercommit"
  "expr": |
    sum(kube_resourcequota:sysdig{job="kubernetes-service-endpoints", type="hard", resource="memory"})
      /
    sum(kube_node_status_allocatable_memory_bytes:sysdig{job="node-exporter"})
      > 1.5
  "for": "5m"
  "labels":
    "severity": "warning"
- "alert": "KubeQuotaFullyUsed"
  "annotations":
    "message": "Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotafullyused"
  "expr": |
    kube_resourcequota:sysdig{job="kubernetes-service-endpoints", type="used"}
      / ignoring(instance, job, type)
    (kube_resourcequota:sysdig{job="kubernetes-service-endpoints", type="hard"} > 0)
      >= 1
  "for": "15m"
  "labels":
    "severity": "info"
- "alert": "CPUThrottlingHigh"
  "annotations":
    "message": "{{ $value | humanizePercentage }} throttling of CPU in namespace {{ $labels.namespace }} for container {{ $labels.container }} in pod {{ $labels.pod }}."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh"
  "expr": |
    sum(increase(container_cpu_cfs_throttled_periods_total:sysdig{container!="", }[5m])) by (container, pod, namespace)
      /
    sum(increase(container_cpu_cfs_periods_total:sysdig{}[5m])) by (container, pod, namespace)
      > ( 25 / 100 )
  "for": "15m"
  "labels":
    "severity": "info"
- "alert": "KubeNodeNotReady"
  "annotations":
    "message": "{{ $labels.node }} has been unready for more than 15 minutes."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubenodenotready"
  "expr": |
    kube_node_status_condition:sysdig{job="kubernetes-service-endpoints",condition="Ready",status="true"} == 0
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeNodeUnreachable"
  "annotations":
    "message": "{{ $labels.node }} is unreachable and some workloads may be rescheduled."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubenodeunreachable"
  "expr": |
    (kube_node_spec_taint:sysdig{job="kubernetes-service-endpoints",key="node.kubernetes.io/unreachable",effect="NoSchedule"} unless ignoring(key,value) kube_node_spec_taint:sysdig{job="kubernetes-service-endpoints",key=~"ToBeDeletedByClusterAutoscaler|cloud.google.com/impending-node-termination|aws-node-termination-handler/spot-itn"}) == 1
  "labels":
    "severity": "warning"
- "alert": "KubeletTooManyPods"
  "annotations":
    "message": "Kubelet '{{ $labels.node }}' is running at {{ $value | humanizePercentage }} of its Pod capacity."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubelettoomanypods"
  "expr": |
    count by(node) (
      (kube_pod_status_phase:sysdig{job="kubernetes-service-endpoints",phase="Running"} == 1) * on(instance,pod,namespace,cluster) group_left(node) topk by(instance,pod,namespace,cluster) (1, kube_pod_info:sysdig{job="kubernetes-service-endpoints"})
    )
    /
    max by(node) (
      kube_node_status_capacity_pods:sysdig{job="kubernetes-service-endpoints"} != 1
    ) > 0.95
  "for": "15m"
  "labels":
    "severity": "warning"
- "alert": "KubeNodeReadinessFlapping"
  "annotations":
    "message": "The readiness status of node {{ $labels.node }} has changed {{ $value }} times in the last 15 minutes."
    "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubenodereadinessflapping"
  "expr": |
    sum(changes(kube_node_status_condition:sysdig{status="true",condition="Ready"}[15m])) by (node) > 2
  "for": "15m"
  "labels":
    "severity": "warning"
