apiVersion: v1
kind: Namespace
metadata:
  name: yace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace-s3-daily
  namespace: yace
spec:
  selector:
    matchLabels:
      app: yace-s3-daily
  replicas: 1
  template:
    metadata:
      labels:
        app: yace-s3-daily
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: yace
        image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.18.0-alpha
        args:
          - "--scraping-interval=7200"
          - "--config.file=/tmp/config.yml"
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: yace-s3-daily-config
            mountPath: /tmp/config.yml
            subPath: config.yml
          - name: yace-s3-credentials
            mountPath: /exporter/.aws/credentials
            subPath: credentials
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            name: yace-s3-daily-config
          name: yace-s3-daily-config
        - secret:
            defaultMode: 420
            secretName: yace-s3-credentials
          name: yace-s3-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace-s3-minute
  namespace: yace
spec:
  selector:
    matchLabels:
      app: yace-s3-minute
  replicas: 1
  template:
    metadata:
      labels:
        app: yace-s3-minute
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: yace
        image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.18.0-alpha
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: yace-s3-minute-config
            mountPath: /tmp/config.yml
            subPath: config.yml
          - name: yace-s3-credentials
            mountPath: /exporter/.aws/credentials
            subPath: credentials
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            name: yace-s3-minute-config
          name: yace-s3-minute-config
        - secret:
            defaultMode: 420
            secretName: yace-s3-credentials
          name: yace-s3-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-s3-daily-config
  namespace: yace
data:
  config.yml: |
    discovery:
      jobs:
      - regions: 
        - us-east-1
        type: s3
        metrics:
          - name: NumberOfObjects
            statistics:
              - Average
            period: 86400
            length: 172800
            additionalDimensions:
              - name: StorageType
                value: AllStorageTypes
          - name: BucketSizeBytes
            statistics:
              - Average
            period: 86400
            length: 172800
            additionalDimensions:
              - name: StorageType
                value: StandardStorage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-s3-minute-config
  namespace: yace
data:
  config.yml: |
    discovery:
      jobs:
      - regions: 
        - us-east-1
        type: s3
        awsDimensions:
          - FilterId
        metrics:
    #      - name: AllRequests
    #        statistics:
    #          - Average
    #        period: 300
    #        length: 36000
    #      - name: GetRequests
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
    #      - name: PutRequests
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
    #      - name: DeleteRequests
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
    #      - name: HeadRequests
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
    #      - name: PostRequests
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
    #      - name: SelectRequests
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
    #      - name: SelectScannedBytes
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
    #      - name: SelectReturnedBytes
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
    #      - name: ListRequests
    #        statistics:
    #          - Sum
    #        period: 300
    #        length: 3600
          - name: BytesDownloaded
            statistics:
              - Sum
              - Average
            period: 300
            length: 3600
          - name: BytesUploaded
            statistics:
              - Sum
              - Average
            period: 300
            length: 3600
          - name: 4xxErrors
            statistics:
              - Average
            period: 300
            length: 3600
          - name: 5xxErrors
            statistics:
              - Average
            period: 300
            length: 3600
          - name: FirstByteLatency
            statistics:
              - p95
            period: 300
            length: 3600
          - name: TotalRequestLatency
            statistics:
              - p95
            period: 300
            length: 3600
    #      - name: ReplicationLatency
    #        statistics:
    #          - Maximum
    #        period: 300
    #        length: 3600
    #      - name: BytesPendingReplication
    #        statistics:
    #          - Maximum
    #        period: 300
    #        length: 3600
    #      - name: OperationsPendingReplication
    #        statistics:
    #          - Maximum
    #        period: 300
    #        length: 3600
---
apiVersion: v1
kind: Secret
metadata:
  name: yace-s3-credentials
  namespace: yace
data:
  # Add in credentials the result of:
  # cat ~/.aws/credentials | base64
  credentials: |
    XXXXX
