{
 "title": "MongoDB_Instance_Health",
 "description": "MongoDB_Instance_Health",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Asserts (errors)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_asserts_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory page faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_extra_info_page_faults_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "DBs Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_mongod_db_data_size_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "mongodb_memory", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_latency_total[5m]) / rate(mongodb_mongod_op_latencies_ops_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Lock Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Lock Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_client",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Global Lock Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_ratio",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Tickets Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets / mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cursors Opened",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_cursor_open{state!='total'}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cursors Timed Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_cursor_timed_out_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_connections{state='available'}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_metrics_num_requests_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{type!='total'}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache Dirty Pages Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (mongodb_mongod_wiredtiger_cache_pages{type='dirty'}) / sum (mongodb_mongod_wiredtiger_cache_pages{type='total'})",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache Evicted Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_connections{state='current'}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "# instances UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(mongodb_up)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Min Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(mongodb_instance_uptime_seconds)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "New Panel", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "## Health & Errors" } },
  { "title": "New Panel (2)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 }, "options": { "content": "## Latency & Cache" } },
  { "title": "New Panel (3)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 }, "options": { "content": "## Networking" } },
  { "title": "New Panel (4)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 }, "options": { "content": "## Locks" } },
  { "title": "New Panel (5)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 }, "options": { "content": "## Database Usage" } },
  {
   "title": "New Panel (6)",
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "✅ Check that there is at least one instance of MongoDB running in your workload.\n\n✅ Check that the minimum uptime to detect restarts of the instances. The number displayed is the running time of the instance restarted more recently.\n\n✅ Check the asserts inside of your instance to detect errors."
   }
  },
  {
   "title": "New Panel (7)",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": {
    "content": "✅ Check that the response time is below your expected latency. \n\n⛳ MongoDB relies on an in-memory cache to minimize the disk operations. Low performance of cache can impact directly the response time. \n\n✅ Check the asserts inside of your instance to detect errors.\n\n⛳ The page memory faults panel shows the total number of page faults that require disk operations. \n* Page faults refer to operations that require the database server to access data that isn’t available in active memory. \n* This value may increase dramatically during moments of poor performance and may correlate with limited memory environments and larger data sets. \n  * 👉 Check the memory usage and ensure that the instance has enough memory\n*  Limited and sporadic page faults do not necessarily indicate an issue"
   }
  },
  {
   "title": "New Panel (8)",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "options": {
    "content": "MongoDB uses locks to manage the shared access to resources. \n\n✅ Check the global lock values:\n* Low values indicate that operations have held the global lock frequently for shorter periods of time. \n* High values indicate that operations have held global lock infrequently for longer periods of time\n\n⛳ The lock queue is the number of operations that have wait for locks. A consistent high value can be a symptom of concurrency issues:\n* ✅ Check that the lock queue has not a sustained high value\n"
   }
  }
 ]
}