apiVersion: v1
kind: SetupGuide
app: Kubernetes control plane
version: 1.0.0
appVersion:
- 1.22.0
configurations:
- name: sysdig-agent.yaml
  file: include/sysdig-agent.yaml
descriptionFile: INSTALLv1.22.md
