{
 "title": "AWS Lambda - Function details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "function",
    "query": "label_values(aws_lambda_invocations_sum,dimension_FunctionName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * aws_lambda_errors_sum{dimension_FunctionName='$function'} / aws_lambda_invocations_sum{dimension_FunctionName='$function'}",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Dead-letter Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_lambda_dead_letter_errors_sum{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Destination Delivery Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_lambda_destination_delivery_failures_sum{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Throttles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_throttles_sum{dimension_FunctionName='$function'}",
     "legendFormat": "Throttles"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_invocations_sum{dimension_FunctionName='$function'}",
     "legendFormat": "Invocations"
    }
   ]
  },
  {
   "title": "Concurrent Executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_concurrent_executions_sum{dimension_FunctionName='$function'}",
     "legendFormat": "Executions"
    }
   ]
  },
  {
   "title": "Unreserved Concurrent Executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_lambda_unreserved_concurrent_executions_sum{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Executions"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_duration_maximum{dimension_FunctionName='$function'}",
     "legendFormat": "Max"
    },
    {
     "expr": "aws_lambda_duration_average{dimension_FunctionName='$function'}",
     "legendFormat": "Average"
    },
    {
     "expr": "aws_lambda_duration_minimum{dimension_FunctionName='$function'}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Iterator Age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(aws_lambda_iterator_age_average{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Average"
    },
    {
     "expr": "sum(aws_lambda_iterator_age_maximum{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Provisioned Concurrency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_lambda_provisioned_concurrency_invocations_sum{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Invocations"
    },
    {
     "expr": "sum(aws_lambda_provisioned_concurrency_executions_sum{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Executions"
    }
   ]
  },
  {
   "title": "Provisioned Concurrency Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(aws_lambda_provisioned_concurrency_utilization_average{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Provisioned Concurrency Spillover",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_lambda_provisioned_concurrency_spillover_invocations_sum{dimension_FunctionName='$function'} or vector(0))",
     "legendFormat": "Invocations"
    }
   ]
  }
 ]
}