apiVersion: v1
kind: Namespace
metadata:
  name: yace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace-lambda
  namespace: yace
spec:
  selector:
    matchLabels:
      app: yace-lambda
  replicas: 1
  template:
    metadata:
      labels:
        app: yace-lambda
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: yace
        image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.18.0-alpha
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: yace-lambda-config
            mountPath: /tmp/config.yml
            subPath: config.yml
          - name: yace-lambda-credentials
            mountPath: /exporter/.aws/credentials
            subPath: credentials
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            name: yace-lambda-config
          name: yace-lambda-config
        - secret:
            defaultMode: 420
            secretName: yace-lambda-credentials
          name: yace-lambda-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-lambda-config
  namespace: yace
data:
  config.yml: |
    discovery:
      jobs:
      - regions: 
        - us-east-1
        type: lambda
        metrics: 
          - name: Duration
            statistics:
            - Sum
            - Maximum
            - Minimum
            - Average
            period: 300
            length: 3600
          - name: Invocations
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: Errors
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: Throttles
            statistics:
            - Sum
            period: 300
            length: 3600  
          - name: DeadLetterErrors
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: DestinationDeliveryFailures
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: ProvisionedConcurrencyInvocations
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: ProvisionedConcurrencySpilloverInvocations
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: IteratorAge
            statistics:
            - Average
            - Maximum
            period: 300
            length: 3600
          - name: ConcurrentExecutions
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: ProvisionedConcurrentExecutions
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: ProvisionedConcurrencyUtilization
            statistics:
            - Maximum
            period: 300
            length: 3600
          - name: UnreservedConcurrentExecutions
            statistics:
            - Sum
            period: 300
            length: 3600
---
apiVersion: v1
kind: Secret
metadata:
  name: yace-lambda-credentials
  namespace: yace
data:
  # Add in credentials the result of:
  # cat ~/.aws/credentials | base64
  credentials: |
    XXXXX
