apiVersion: v1
kind: Alert
app: mssql
version: 1.0.0
appVersion:
- '2019'
configurations:
- kind: Prometheus
  data: |
    - alert: DatabaseDown
      expr: up{job="mssql"} == 0
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Connection with database not available
    - alert: SqlServerDeadlock
      expr: increase(mssql_deadlocks[1m]) > 5
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: SQL Server deadlock (instance {{ $labels.instance }})
        description: SQL Server is having some deadlock.
    - alert: SqlDiskIsRunningOut
      expr: sum(mssql_disk_space_avaiable_bytes_total{job=~"mssql"})/sum(mssql_disk_space_total_bytes_total{job=~"mssql"}) > 0.85
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: SQL disk is running out (instance {{ $labels.instance }})
        description: SQL disk is running out.
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "up{job=\"mssql\"} == 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "DatabaseDown",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "increase(mssql_deadlocks[1m]) > 5",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "SqlServerDeadlock",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 0,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "sum(mssql_disk_space_avaiable_bytes_total{job=~\"mssql\"})/sum(mssql_disk_space_total_bytes_total{job=~\"mssql\"})  < 0.85",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "SqlDiskIsRunningOut",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 0,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
descriptionFile: ALERTS.md