{
 "title": "AWS SQS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "queue",
    "query": "label_values(aws_sqs_number_of_messages_received_sum,dimension_QueueName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aws_sqs_number_of_messages_received_sum{dimension_QueueName=~\"$queue\"})"
    }
   ]
  },
  {
   "title": "Age of oldest message",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_age_of_oldest_message_maximum{dimension_QueueName=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Empty Receives",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_number_of_empty_receives_sum{dimension_QueueName=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Messages Deleted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_deleted_sum{dimension_QueueName=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Messages Delayed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_average{dimension_QueueName=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Messages Not Visible",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_average{dimension_QueueName=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Messages Visible",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_average{dimension_QueueName=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_received_sum{dimension_QueueName=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_sent_sum{dimension_QueueName=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Queue Message Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_sqs_sent_message_size_sum{dimension_QueueName=~\"$queue\"}"
    }
   ]
  }
 ]
}