{
 "title": "Oracle DB",
 "time": { "from": "2020-09-09T05:38:56.730Z", "to": "2020-09-09T05:50:28.409Z" },
 "panels": [
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_activity_execute_count[$__interval])",
     "legendFormat": "Execs"
    },
    {
     "expr": "rate(oracledb_activity_parse_count_total[$__interval])",
     "legendFormat": "Parses"
    },
    {
     "expr": "rate(oracledb_activity_user_commits[$__interval])",
     "legendFormat": "User Commits"
    },
    {
     "expr": "rate(oracledb_activity_user_rollbacks[$__interval])",
     "legendFormat": "User Rollbacks"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(oracledb_sessions_value)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (resource_name)(oracledb_resource_current_utilization / oracledb_resource_limit_value)"
    }
   ]
  },
  {
   "title": "Tablespaces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (tablespace) (oracledb_tablespace_bytes /(oracledb_tablespace_bytes + oracledb_tablespace_free))"
    }
   ]
  },
  {
   "title": "Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "oracledb_wait_time_administrative",
     "legendFormat": "Administrative"
    },
    { "expr": "oracledb_wait_time_application", "legendFormat": "Application" },
    { "expr": "oracledb_wait_time_commit", "legendFormat": "Commit" },
    { "expr": "oracledb_wait_time_concurrency", "legendFormat": "Concurrency" },
    {
     "expr": "oracledb_wait_time_configuration",
     "legendFormat": "Configuration"
    },
    { "expr": "oracledb_wait_time_network", "legendFormat": "Network" },
    { "expr": "oracledb_wait_time_other", "legendFormat": "Other" },
    { "expr": "oracledb_wait_time_scheduler", "legendFormat": "Scheduler" },
    { "expr": "oracledb_wait_time_system_io", "legendFormat": "System IO" },
    { "expr": "oracledb_wait_time_user_io", "legendFormat": "User IO" }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "oracledb_slow_queries_p95_time_usecs",
     "legendFormat": "p95"
    },
    {
     "expr": "oracledb_slow_queries_p99_time_usecs",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Big Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "oracledb_big_queries_p95_rows", "legendFormat": "p95" },
    { "expr": "oracledb_big_queries_p99_rows", "legendFormat": "p99" }
   ]
  },
  {
   "title": "Top DBA Tables",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,oracledb_size_dba_segments_top100_table_bytes)",
     "legendFormat": "{{segment_name}}"
    }
   ]
  },
  {
   "title": "Top DBA Table Partitions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,oracledb_size_dba_segments_top100_table_partition_bytes)",
     "legendFormat": "{{segment_name}}"
    }
   ]
  },
  {
   "title": "Top DBA Cluster Tables",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,oracledb_size_dba_segments_top100_cluster_bytes)",
     "legendFormat": "{{segment_name}}"
    }
   ]
  },
  {
   "title": "Top User Tables",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,oracledb_size_user_segments_top100_table_bytes)",
     "legendFormat": "{{segment_name}}"
    }
   ]
  },
  {
   "title": "Top User Table Partitions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,oracledb_size_user_segments_top100_table_partition_bytes)",
     "legendFormat": "{{segment_name}}"
    }
   ]
  },
  {
   "title": "Top User Cluster Tables",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,oracledb_size_user_segments_top100_cluster_bytes)",
     "legendFormat": "{{segment_name}}"
    }
   ]
  }
 ]
}