{
 "title": "Postgresql_DB_Golden_Signals",
 "description": "Postgresql_DB_Golden_Signals",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "bottomk(20,100 * avg by (datname,server)(rate(pg_stat_database_blks_hit{datname!=''}[5m]) / (rate(pg_stat_database_blks_hit{datname!=''}[5m]) + rate(pg_stat_database_blks_read{datname!=''}[5m]))))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Fetched / Returned Tuples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * (rate(pg_stat_database_tup_fetched{datname!=''}[5m]) / rate(pg_stat_database_tup_returned{datname!=''}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "🔒 Locks by Mode ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(20,rate(pg_locks_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "🔒⚠️ Query Locks Errors ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_conflicts_confl_lock[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(pg_stat_database_conflicts_confl_deadlock[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "🔒☠️ Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{datname!=''}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Connections by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(20,rate(pg_stat_activity_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Max Duration by State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(20,rate(pg_stat_activity_max_tx_duration[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "File Read Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(20,rate(pg_stat_database_blk_read_time{datname!=''}[5m]) / rate(pg_stat_database_blks_read{datname!=''}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(20,rate(pg_stat_database_xact_commit[5m]))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "topk(20,rate(pg_stat_database_xact_rollback[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Fetched / Returned Tuples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "IOPS by Function",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname!=''}[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{datname!=''}[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname!=''}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Data Written to Temporary Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_bytes{datname!=''}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(20,pg_database_size_bytes)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Heap Only Tuple Updates Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * sum by (datname,server)(rate(pg_stat_user_tables_n_tup_hot_upd[5m])) / (sum by (datname,server)(rate(pg_stat_user_tables_n_tup_hot_upd[5m])) + sum by (datname,server)(rate(pg_stat_database_tup_updated[5m]))) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Index vs Sequential Scans",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (datname,server)(pg_stat_user_tables_idx_scan) or vector(0)",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum by (datname,server)(pg_stat_user_tables_seq_scan) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Backends connected",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum((pg_stat_database_numbackends))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}