---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
spec:
  selector:
    matchLabels:
      app: redis-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-exporter
      annotations:
        promcat.sysdig.com/integration_type: redis
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
      - name: redis-exporter
        image: quay.io/sysdig/redis-exporter:latest
        ports:
          - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: redis://redis:6379
        - name: REDIS_USER
          valueFrom:
            secretKeyRef:
              name: redis-exporter-auth
              key: user
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-exporter-auth
              key: password
        resources:
          limits:
            memory: "256Mi"
            cpu: "256m"