apiVersion: v1
kind: SetupGuide
app: "nginx-ingress"
version: 1.0.0
appVersion:
- latest
descriptionFile: INSTALL.md
configurations:
- name: nginx-ingress-deploy.yaml
  file: include/nginx-ingress-deploy.yaml