{
 "title": "Apache App Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "app", "query": "label_values(apache_up,app)" }
  ]
 },
 "panels": [
  {
   "title": "Instances Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(apache_up{app='$app'})" }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "max(apache_uptime_seconds_total{app='$app'})"
    }
   ]
  },
  {
   "title": "Time since last OK request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "min(time() - apache_http_last_request_seconds{app='$app',code=~\"2..\"})"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(apache_http_response_codes_total{app='$app',code=~'4..|5..'}[5m])) / sum(rate(apache_http_response_codes_total{app='$app'}[5m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_duration_total{app='$app'}[5m])) / sum(rate(apache_accesses_total{app='$app'}[5m]))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "% Workers Busy by Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum by (instance)(apache_workers{app='$app',state='busy'}) / sum by (instance)(apache_workers{app='$app'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scoreboard status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (state)(apache_scoreboard{app='$app'})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU Load by Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(apache_cpuload{app='$app'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections by State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (state)(apache_connections{app='$app'})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Requests per Second by Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(rate(apache_http_response_codes_total{app='$app'}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_sent_kilobytes_total{app='$app'}[5m]))",
     "legendFormat": "KBs"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_sent_kilobytes_total{app='$app'}[5m])) / sum(rate(apache_accesses_total[5m]))",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}