{
 "title": "HAProxy K8s Ingress Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(time() - haproxy_process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "count(haproxy_process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Frontend OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count by (proxy) (haproxy_frontend_status == 1)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend FULL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (proxy) (haproxy_frontend_status == 2) or vector(0)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend STOPPED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "count by (proxy) (haproxy_frontend_status == 0 ) or vector(0)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Backend DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count by (proxy) (haproxy_backend_status == 0) or vector(0)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Connections and Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_process_current_connection_rate)",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(haproxy_process_current_session_rate)",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "SSL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_process_ssl_connections_total[5m]))",
     "legendFormat": "conns"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(haproxy_process_jobs)", "legendFormat": "jobs" }
   ]
  },
  {
   "title": "Request and Response Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_requests_denied_total[5m]))",
     "legendFormat": "Requests Denied"
    },
    {
     "expr": "sum(rate(haproxy_frontend_responses_denied_total[5m]))",
     "legendFormat": "Responses Denied"
    },
    {
     "expr": "sum(rate(haproxy_frontend_request_errors_total[5m]))",
     "legendFormat": "Request Error"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_process_current_tasks)",
     "legendFormat": "tasks"
    }
   ]
  },
  {
   "title": "Active and Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_process_active_peers)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(haproxy_process_connected_peers)",
     "legendFormat": "Connected"
    }
   ]
  },
  {
   "title": "Process Run Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_process_current_run_queue)",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Connection ans Session Denied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_denied_connections_total[5m]))",
     "legendFormat": "Connection Denied"
    },
    {
     "expr": "sum(rate(haproxy_frontend_denied_sessions_total[5m]))",
     "legendFormat": "Session Denied"
    }
   ]
  },
  {
   "title": "Frontend Bytes In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (proxy) (rate(haproxy_frontend_bytes_in_total[5m]))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (proxy) (rate(haproxy_frontend_connections_total[5m]))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend Bytes Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (proxy) (rate(haproxy_frontend_bytes_out_total[5m]))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend Requests (TCP and HTTP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (proxy)(rate(haproxy_frontend_connections_total[5m]))",
     "legendFormat": "{{proxy}}"
    }
   ]
  }
 ]
}
{
 "title": "HAProxy Proxy Golden Signals",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "proxy",
    "query": "label_values(haproxy_backend_sessions_total,proxy)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(haproxy_backend_status{proxy='$proxy'}==1 or vector(0))"
    }
   ]
  },
  {
   "title": "Instances Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(haproxy_backend_status{proxy='$proxy'}==0 or vector(0))"
    }
   ]
  },
  {
   "title": "Sessions Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * max(rate(haproxy_backend_sessions_total{proxy='$proxy'}[5m]) / haproxy_backend_limit_sessions{proxy='$proxy'})",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Queued Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(haproxy_backend_current_queue{proxy='$proxy'})",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(haproxy_backend_http_responses_total{code!=\"2xx\",proxy='$proxy'}[5m])) / sum(rate(haproxy_backend_http_responses_total{proxy='$proxy'}[5m])) ",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Denial Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_requests_denied_total{proxy=\"$proxy\"}[5m])) / sum(rate(haproxy_backend_http_requests_total{proxy=\"$proxy\"}[5m]))",
     "legendFormat": "Requets"
    },
    {
     "expr": "sum(rate(haproxy_backend_responses_denied_total{proxy=\"$proxy\"}[5m])) / sum(rate(haproxy_backend_http_responses_total{proxy=\"$proxy\"}[5m]))",
     "legendFormat": "Responses"
    }
   ]
  },
  {
   "title": "HTTP Error by Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{code!=\"2xx\",proxy='$proxy'}[5m])) ",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Data Transfers Aborted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_client_aborts_total{proxy=\"$proxy\"}[5m])) ",
     "legendFormat": "By Client"
    },
    {
     "expr": "sum(rate(haproxy_backend_server_aborts_total{proxy=\"$proxy\"}[5m])) ",
     "legendFormat": "By Server"
    }
   ]
  },
  {
   "title": "Mean Response Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(haproxy_backend_response_time_average_seconds{proxy=\"$proxy\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean Connect and Queue Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(haproxy_backend_queue_time_average_seconds{proxy=\"$proxy\"})",
     "legendFormat": "Queue Time"
    },
    {
     "expr": "max(haproxy_backend_connect_time_average_seconds{proxy=\"$proxy\"})",
     "legendFormat": "Connect Time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{proxy=\"$proxy\"}[5m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{proxy=\"$proxy\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=\"$proxy\"}[5m]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Request and Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{proxy=\"$proxy\"}[5m])) / sum(rate(haproxy_backend_http_requests_total{proxy=\"$proxy\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{proxy=\"$proxy\"}[5m])) / sum(rate(haproxy_backend_http_responses_total{proxy=\"$proxy\"}[5m])) ",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}