{
 "title": "Ocp4 / API server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(apiserver_request_total, cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(apiserver_request_total{job=\"apiserver\", cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up:kubernetes{job=\"apiserver\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total:kubernetes_apiservers{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total:kubernetes_apiservers{code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total:kubernetes_apiservers{code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total:kubernetes_apiservers{code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "apiserver_request_duration_seconds_bucket:kubernetes_apiservers{verb!=\"WATCH\"}",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total:kubernetes_apiservers[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth:kubernetes_apiservers[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workqueue_queue_duration_seconds_bucket:kubernetes_apiservers",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Entry Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_helper_cache_entry_total:kubernetes_apiservers[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Hit/Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_helper_cache_hit_total:kubernetes_apiservers[5m])) by (instance)",
     "legendFormat": "{{instance}} hit"
    },
    {
     "expr": "sum(rate(etcd_helper_cache_miss_total:kubernetes_apiservers[5m])) by (instance)",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "ETCD Cache Duration 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "etcd_request_cache_get_duration_seconds_bucket:kubernetes_apiservers",
     "legendFormat": "{{instance}} get"
    },
    {
     "expr": "etcd_request_cache_add_duration_seconds_bucket:kubernetes_apiservers",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes:kubernetes{job=\"apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total:kubernetes{job=\"apiserver\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines:kubernetes{job=\"apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}