{
 "title": "AWS EBS Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Errors / Saturation",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(aws_ebs_volume_queue_length_average)"
    }
   ]
  },
  {
   "title": "Volumes With Queue Not Empty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "count(aws_ebs_volume_queue_length_average > 0) or vector(0)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "100% Idle Time Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "count(aws_ebs_volume_idle_time_sum / 300 >= 1) or vector(0)"
    }
   ]
  },
  {
   "title": "IOPS SSD Perform. < 99.9%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "count(aws_ebs_volume_throughput_percentage_average < 99.9) or vector(0)"
    }
   ]
  },
  {
   "title": "Volumes With Zero Bust Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "count(aws_ebs_burst_balance_minimum == 0) or vector(0)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Top 5 Queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_ebs_volume_queue_length_average)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Bottom 5 Burst Balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bottomk(5,aws_ebs_burst_balance_minimum)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Top 5 Read Operations Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_ebs_volume_read_ops_sum / 300)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Top 5 Write Operations Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_ebs_volume_write_ops_sum / 300)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Top 5 Read Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_ebs_volume_read_bytes_sum / 300)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Top 5 Write Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_ebs_volume_write_bytes_sum / 300)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Top 5 Mean Read Operation Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_ebs_volume_total_read_time_sum / aws_ebs_volume_read_ops_sum)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Top 5 Mean Write Operation Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_ebs_volume_total_write_time_sum / aws_ebs_volume_write_ops_sum)",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  }
 ]
}