{
 "title": "Docker engine",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(engine_daemon_engine_info,instance)"
   },
   {
    "name": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU numbers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_cpus_cpus{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "engine_daemon_events_subscribers_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Builds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "builder_builds_triggered_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Builds failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(builder_builds_failed_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Containers running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Containers status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Time x Network Action percentile",
   "type": "graph",
   "description": "Measuring some percentiles performance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_daemon_network_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{action}} 99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(engine_daemon_network_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{action}} 90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 50"
    },
    {
     "expr": "histogram_quantile(0.25, rate(engine_daemon_network_actions_seconds_bucket{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{action}} 25"
    }
   ]
  },
  {
   "title": "Total Container Actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Builds failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "builder_builds_failed_total{instance=~\"$instance\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Network actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_network_actions_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}