{
 "title": "Istio Workload Dashboard Sysdig",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Incoming Request Volume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total:sysdig{reporter=\"destination\"}[5m])) by (destination_workload)",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(irate(istio_requests_total:sysdig{reporter=\"destination\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total:sysdig{reporter=\"destination\"}[5m])))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:histogram50",
     "legendFormat": "P50  {{destination_service_name}}"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:histogram90",
     "legendFormat": "P90  {{destination_service_name}}"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:histogram99",
     "legendFormat": "P99  {{destination_service_name}}"
    }
   ]
  },
  {
   "title": "TCP Server Traffic",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{reporter=\"destination\"}[1m]))+sum(irate(istio_tcp_received_bytes_total:sysdig{reporter=\"destination\"}[1m]))"
    }
   ]
  },
  {
   "title": "TCP Client Traffic",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{reporter=\"source\"}[1m]))+sum(irate(istio_tcp_received_bytes_total:sysdig{reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "Incoming Requests by Source And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy=\"mutual_tls\", reporter=\"destination\"}[5m])) by (source_workload, source_workload_namespace, response_code)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy!=\"mutual_tls\", reporter=\"destination\"}[5m])) by (source_workload, source_workload_namespace, response_code)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total:sysdig{reporter=\"destination\", connection_security_policy=\"mutual_tls\", response_code!~\"5.*\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total:sysdig{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total:sysdig{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", response_code!~\"5.*\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total:sysdig{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Duration by Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total:sysdig{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total:sysdig{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{connection_security_policy=\"mutual_tls\", reporter=\"destination\"}[1m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{connection_security_policy!=\"mutual_tls\", reporter=\"destination\"}[1m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests by Destination And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy=\"mutual_tls\", reporter=\"source\"}[5m])) by (destination_service, response_code)",
     "legendFormat": "{{ destination_service }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy!=\"mutual_tls\", reporter=\"source\"}[5m])) by (destination_service, response_code)",
     "legendFormat": "{{ destination_service }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Outgoing Success Rate (non-5xx responses) By Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[5m])) by (destination_service)",
     "legendFormat": "{{ destination_service }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[5m])) by (destination_service)",
     "legendFormat": "{{destination_service }}"
    }
   ]
  },
  {
   "title": "Outgoing Request Duration by Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bydestination:mutual_tls:histogram50",
     "legendFormat": "{{ destination_service }} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bydestination:mutual_tls:histogram90",
     "legendFormat": "{{ destination_service }} P90 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bydestination:mutual_tls:histogram95",
     "legendFormat": "{{ destination_service }} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bydestination:mutual_tls:histogram99",
     "legendFormat": "{{ destination_service }} P99 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bydestination:not_mutual_tls:histogram50",
     "legendFormat": "{{ destination_service }} P50"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bydestination:not_mutual_tls:histogram90",
     "legendFormat": "{{ destination_service }} P90"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bydestination:not_mutual_tls:histogram95",
     "legendFormat": "{{ destination_service }} P95"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bydestination:not_mutual_tls:histogram99",
     "legendFormat": "{{ destination_service }} P99"
    }
   ]
  },
  {
   "title": "Outgoing Request Size By Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "istio_request_bytes_bucket:source:bydestination:mutual_tls:histogram50",
     "legendFormat": "{{ destination_service }} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bydestination:mutual_tls:histogram90",
     "legendFormat": "{{ destination_service }} P90 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bydestination:mutual_tls:histogram95",
     "legendFormat": "{{ destination_service }} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bydestination:mutual_tls:histogram99",
     "legendFormat": "{{ destination_service }} P99 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bydestination:not_mutual_tls:histogram50",
     "legendFormat": "{{ destination_service }} P50"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bydestination:not_mutual_tls:histogram90",
     "legendFormat": "{{ destination_service }} P90"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bydestination:not_mutual_tls:histogram95",
     "legendFormat": "{{ destination_service }} P95"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bydestination:not_mutual_tls:histogram99",
     "legendFormat": "{{ destination_service }} P99"
    }
   ]
  },
  {
   "title": "Response Size By Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "istio_response_bytes_bucket:source:bydestination:mutual_tls:histogram50",
     "legendFormat": "{{ destination_service }} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bydestination:mutual_tls:histogram90",
     "legendFormat": "{{ destination_service }} P90 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bydestination:mutual_tls:histogram95",
     "legendFormat": "{{ destination_service }} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bydestination:mutual_tls:histogram99",
     "legendFormat": "{{ destination_service }}  P99 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bydestination:not_mutual_tls:histogram50",
     "legendFormat": "{{ destination_service }} P50"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bydestination:not_mutual_tls:histogram90",
     "legendFormat": "{{ destination_service }} P90"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bydestination:not_mutual_tls:histogram95",
     "legendFormat": "{{ destination_service }} P95"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bydestination:not_mutual_tls:histogram99",
     "legendFormat": "{{ destination_service }} P99"
    }
   ]
  },
  {
   "title": "Bytes Sent on Outgoing TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{connection_security_policy=\"mutual_tls\", reporter=\"source\"}[1m])) by (destination_service)",
     "legendFormat": "{{ destination_service }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{connection_security_policy!=\"mutual_tls\", reporter=\"source\"}[1m])) by (destination_service)",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  {
   "title": "Bytes Received from Outgoing TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_service)",
     "legendFormat": "{{ destination_service }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total:sysdig{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_service)",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  }
 ]
}