{
 "title": "Istio Service Dashboard Sysdig",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Client Request Volume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_service_name)(irate(istio_requests_total:sysdig{reporter=\"source\"}[5m]))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Client Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(sum by (destination_service_name)(irate(istio_requests_total:sysdig{reporter=\"source\",response_code!~\"5.*\"}[5m])) / sum by (destination_service_name)(irate(istio_requests_total:sysdig{reporter=\"source\"}[5m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Client Request Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:histogram50",
     "legendFormat": "P50- {{destination_service_name}}"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:histogram90",
     "legendFormat": "P90- {{destination_service_name}}"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:histogram99",
     "legendFormat": "P99- {{destination_service_name}}"
    }
   ]
  },
  {
   "title": "TCP Received Bytes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total:sysdig{reporter=\"source\"}[1m]))",
     "legendFormat": "{{destination_service}}"
    }
   ]
  },
  {
   "title": "Server Request Volume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_service_name)(irate(istio_requests_total:sysdig{reporter=\"destination\"}[5m]))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Server Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(sum by (destination_service_name)(irate(istio_requests_total:sysdig{reporter=\"destination\",response_code!~\"5.*\"}[5m])) / sum by (destination_service_name)(irate(istio_requests_total:sysdig{reporter=\"destination\"}[5m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Server Request Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:histogram50",
     "legendFormat": "p50- {{destination_service_name}}"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:histogram90",
     "legendFormat": "P90- {{destination_service_name}}"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:histogram99",
     "legendFormat": "P99- {{destination_service_name}}"
    }
   ]
  },
  {
   "title": "TCP Sent Bytes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "Incoming Requests by Source And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy=\"mutual_tls\",reporter=\"source\"}[5m])) by (source_workload, source_workload_namespace, response_code)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy!=\"mutual_tls\",reporter=\"source\"}[5m])) by (source_workload, source_workload_namespace, response_code)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "100*(sum(irate(istio_requests_total:sysdig{reporter=\"source\", connection_security_policy=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total:sysdig{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[5m])) by (source_workload, source_workload_namespace))",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "100*(sum(irate(istio_requests_total:sysdig{reporter=\"source\", connection_security_policy!=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total:sysdig{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[5m])) by (source_workload, source_workload_namespace))",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Duration by Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bysource:mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bysource:mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bysource:mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bysource:mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:source:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "istio_request_bytes_bucket:source:bysource:mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bysource:mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bysource:mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bysource:mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "istio_request_bytes_bucket:source:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "istio_response_bytes_bucket:source:bysource:mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bysource:mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bysource:mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bysource:mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "istio_response_bytes_bucket:source:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total:sysdig{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total:sysdig{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy=\"mutual_tls\",reporter=\"source\"}[5m])) by (source_workload, source_workload_namespace, response_code)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy!=\"mutual_tls\",reporter=\"source\"}[5m])) by (source_workload, source_workload_namespace, response_code)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Incoming Requests by Destination And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy=\"mutual_tls\",reporter=\"destination\"}[5m])) by (destination_workload, destination_workload_namespace, response_code)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total:sysdig{connection_security_policy!=\"mutual_tls\",reporter=\"destination\"}[5m])) by (destination_workload, destination_workload_namespace, response_code)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "100*(sum(irate(istio_requests_total:sysdig{reporter=\"destination\", connection_security_policy=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total:sysdig{reporter=\"destination\", connection_security_policy=\"mutual_tls\"}[5m])) by (destination_workload, destination_workload_namespace))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "100*(sum(irate(istio_requests_total:sysdig{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",response_code!~\"5.*\"}[5m])) by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total:sysdig{reporter=\"destination\", connection_security_policy!=\"mutual_tls\"}[5m])) by (destination_workload, destination_workload_namespace))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Duration by Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:mutual_tls:histogram50",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:mutual_tls:histogram90",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:mutual_tls:histogram95",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:mutual_tls:histogram99",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99 (🔐mTLS)"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "istio_request_duration_milliseconds_bucket:destination:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:mutual_tls:histogram50",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:mutual_tls:histogram90",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P90 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:mutual_tls:histogram95",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:mutual_tls:histogram99",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P99 (🔐mTLS)"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "istio_request_bytes_bucket:destination:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:mutual_tls:histogram50",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:mutual_tls:histogram90",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P90 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:mutual_tls:histogram95",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:mutual_tls:histogram99",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P99 (🔐mTLS)"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:not_mutual_tls:histogram50",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:not_mutual_tls:histogram90",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:not_mutual_tls:histogram95",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "istio_response_bytes_bucket:destination:bysource:not_mutual_tls:histogram99",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\"}[1m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{connection_security_policy=\"mutual_tls\", reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload }}.{{destination_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total:sysdig{connection_security_policy!=\"mutual_tls\", reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload }}.{{destination_workload_namespace }}"
    }
   ]
  }
 ]
}