groups:
    - name: Kafka
      rules:
        - alert: '[Kafka] Broker Down'
          expr: |
            sum (kube_workload_status_desired)-sum (kafka_brokers) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            description: There are less Kafka brokers up than expected. The 'workload' label of the Kafka Deployment/Stateful set must be specified.
        - alert: '[Kafka] No Leader'
          expr: |
            sum(kafka_controller_active_controller) < 1
          for: 5m
          labels:
            severity: critical
          annotations:
            description: There is no ActiveController or 'leader' in the Kafka cluster.
        - alert: '[Kafka] Too Many Leaders'
          expr: |
            sum(kafka_controller_active_controller) > 1
          for: 10m
          labels:
            severity: critical
          annotations:
            description: There is more than one ActiveController or 'leader' in the Kafka cluster.
        - alert: '[Kafka] Offline Partitions'
          expr: |
            sum(kafka_controller_offline_partitions) > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            description: There are one or more Offline Partitions. These partitions don’t have an active leader and are hence not writable or readable.
        - alert: '[Kafka] Under Replicated Partitions'
          expr: |
            sum(kafka_server_under_replicated_partitions) > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            description: There are one or more Under Replicated Partitions.
        - alert: '[Kafka] Under In-Sync Replicated Partitions'
          expr: |
            sum(kafka_server_under_isr_partitions) > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            description: There are one or more Under In-Sync Replicated Partitions. These partitions will be unavailable to producers who use 'acks=all'.
        - alert: '[Kafka] ConsumerGroup Lag Not Decreasing'
          expr: |
            (sum (kafka__lag) > 0)and (sum (delta(kafka__lag[2m])) >= 0)
          for: 15m
          labels:
            severity: warning
          annotations:
            description: The ConsumerGroup lag is not decreasing. The Consumers might be down, failing to process the messages and continuously retrying, or their consumption rate is lower than the production rate of messages.
        - alert: '[Kafka] ConsumerGroup Without Members'
          expr: |
            sum (kafka__members) == 0
          for: 10m
          labels:
            severity: info
          annotations:
            description: The ConsumerGroup doesn't have any members.
        - alert: '[Kafka] Producer High ThrottleTime By Client-Id'
          expr: |
            max (kafka_server_producer_client_throttle_time) > 1000
          for: 5m
          labels:
            severity: warning
          annotations:
            description: The Producer has reached its quota and has high throttle time. Applicable when Client-Id-only quotas are being used.
        - alert: '[Kafka] Producer High ThrottleTime By User'
          expr: |
            max (kafka_server_producer__throttle_time) > 1000
          for: 5m
          labels:
            severity: warning
          annotations:
            description: The Producer has reached its quota and has high throttle time. Applicable when User-only quotas are being used.
        - alert: '[Kafka] Producer High ThrottleTime By User And Client-Id'
          expr: |
            max (kafka_server_producer__client_throttle_time) > 1000
          for: 5m
          labels:
            severity: warning
          annotations:
            description: The Producer has reached its quota and has high throttle time. Applicable when Client-Id + User quotas are being used.
        - alert: '[Kafka] Consumer High ThrottleTime By Client-Id'
          expr: |
            max (kafka_server_consumer_client_throttle_time) > 1000
          for: 5m
          labels:
            severity: warning
          annotations:
            description: The Consumer has reached its quota and has high throttle time. Applicable when Client-Id-only quotas are being used.
        - alert: '[Kafka] Consumer High ThrottleTime By User'
          expr: |
            max (kafka_server_consumer__throttle_time) > 1000
          for: 5m
          labels:
            severity: warning
          annotations:
            description: The Consumer has reached its quota and has high throttle time. Applicable when User-only quotas are being used.
        - alert: '[Kafka] Consumer High ThrottleTime By User And Client-Id'
          expr: |
            max (kafka_server_consumer__client_throttle_time) > 1000
          for: 5m
          labels:
            severity: warning
          annotations:
            description: The Consumer has reached its quota and has high throttle time. Applicable when Client-Id + User quotas are being used.
