{
 "title": "Fluentd",
 "description": "Fluentd",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Output Error/Retry/Rollback rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(fluentd_output_status_num_errors[5m]))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum (rate(fluentd_output_status_retry_count[5m]))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum (rate(fluentd_output_status_rollback_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Total Output rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(fluentd_output_status_emit_records[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Total Input rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(fluentd_input_status_num_records_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Maximum Buffer Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( type, plugin_id)(max_over_time(fluentd_output_status_buffer_queue_length[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Maximum Buffer Bytes\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( type, plugin_id)(max_over_time(fluentd_output_status_buffer_total_bytes[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Top 50 Input rate per container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(50, sum by ( input_namespace, input_pod, input_container)(rate(fluentd_input_status_num_records_total[5m]))> 0) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Flush time\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( type, plugin_id)(rate(fluentd_output_status_flush_time_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Flushes per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( type, plugin_id)(rate(fluentd_output_status_emit_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Maximum Buffer Queue Length per instance\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , type, plugin_id)(max_over_time(fluentd_output_status_buffer_queue_length[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Buffer Available Space Ratio per instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "min by( , type, plugin_id)(min_over_time(fluentd_output_status_buffer_available_space_ratio[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Top 50 Output rate per plugin",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(50, sum by ( type, plugin_id)(rate(fluentd_output_status_emit_records[5m])))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Output Error/Retry/Rollback rate per plugin",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by ( type, plugin_id)(rate(fluentd_output_status_num_errors[5m]))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum by ( type, plugin_id)(rate(fluentd_output_status_retry_count[5m]))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum by ( type, plugin_id)(rate(fluentd_output_status_rollback_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Output Retry Wait per plugin",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by ( type, plugin_id)(max_over_time(fluentd_output_status_retry_wait[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Output Error ratio per plugin",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by ( type, plugin_id)(rate(fluentd_output_status_num_errors[5m])) / sum by( type, plugin_id)(rate(fluentd_output_status_emit_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Slow Flush ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( type, plugin_id)(rate(fluentd_output_status_slow_flush_count[5m])) / sum by( type, plugin_id)(rate(fluentd_output_status_emit_count[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Scope details",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "👉 The 'input_namespace' , 'input_pod' and 'input_container' scopes can be used in the 'Input' panels to filter the sources of the logs.\n\n👉 The 'output_type' and 'output_plugin_id' scopes  allows filtering by 'Output' in the rest of the panels. More info about 'Outputs' in the **[Fluentd official documentation](https://docs.fluentd.org/output)**."
   }
  },
  { "title": "Buffer", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 }, "options": { "content": "# Buffer" } },
  { "title": "Flush", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 52 }, "options": { "content": "# Flush" } },
  { "title": "Input / Output (2)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 }, "options": { "content": "# Input / Output" } }
 ]
}