{
 "title": "Kubernetes Proxy",
 "description": "Kubernetes Proxy",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{ =~ $cluster}[5m])) by (verb, url, le))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"2..\"}[5m]))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"3..\"}[5m])) ",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"4..\"}[5m])) ",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"5..\"}[5m])) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{ =~ $cluster}[5m])) by (verb, url, le))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Programming Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kubeproxy_network_programming_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Rules Sync Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubeproxy_sync_proxy_rules_duration_seconds_count[5m])) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Rule Sync Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Programming Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubeproxy_network_programming_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "UP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "{{ handler }}" }
   ]
  }
 ]
}