{
 "title": "Kubernetes CoreDNS",
 "description": "Kubernetes CoreDNS",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rcode rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total[5m])) by (rcode)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests (by type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(rate(coredns_dns_requests_total[5m])) by (type))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket[5m])) by (server, zone, le))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(rate(coredns_dns_requests_total[5m]) ) by (zone))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total[5m])) by (type)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_misses_total[5m])) by(server)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"kube-dns-default|openshift-dns-default\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"kube-dns-default|openshift-dns-default\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"kube-dns-default|openshift-dns-default\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests (by protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(rate(coredns_dns_requests_total[5m]) ) by (proto))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Forward Request duration 99th quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket[5m])) by (to, le))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket[5m])) by (server, zone, proto, le))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket[5m])) by (server, zone, proto, le))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket[5m])) by (server, zone, proto, le))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket[5m])) by (server, zone, proto, le))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "UP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{job=~\"kube-dns-default|openshift-dns-default\"})",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(coredns_panics_total)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Cached",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_hits_total) / (sum(coredns_cache_misses_total) + sum(coredns_cache_hits_total))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Plugins Enabled",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(sum(coredns_plugin_enabled) by (name))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}