apiVersion: v1
kind: Alert
app: Harbor
version: 1.0.0
appVersion:
- '1.1'
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: Harbor
      rules:
      - alert: HarborIsDown
        expr: harbor_up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: The service of Harbor is Down
      - alert: ProjectQuotaIsRaisingTheLimit
        expr: harbor_quotas_size_bytes{type="used"} / ignoring(type) harbor_quotas_size_bytes{type="hard"} > 0.95
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: The quota of the repository {{ $labels.repo_name }} is getting close to the limit
