{
 "title": "Harbor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "harbor_up" }
   ]
  },
  {
   "title": "Total projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "harbor_project_count_total{type=\"total_project\"}"
    }
   ]
  },
  {
   "title": "Private projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "harbor_project_count_total{type=\"public_project\"}"
    }
   ]
  },
  {
   "title": "Public projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "harbor_project_count_total{type=\"public_project\"}"
    }
   ]
  },
  {
   "title": "Project quota usage: storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "harbor_quotas_size_bytes", "legendFormat": "{{repo_name}}: {{type}}" }
   ]
  },
  {
   "title": "Project quota usage: repository count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "harbor_quotas_count_total", "legendFormat": "{{repo_name}}: {{type}}" }
   ]
  },
  {
   "title": "Replication status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(harbor_replication_status) / count(harbor_replication_status)"
    }
   ]
  },
  {
   "title": "Tasks succeeded",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(harbor_replication_tasks{result=\"succeed\"})"
    }
   ]
  },
  {
   "title": "Tasks in progress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(harbor_replication_tasks{result=\"in_progress\"})"
    }
   ]
  },
  {
   "title": "Tasks failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(harbor_replication_tasks{result=\"failed\"})"
    }
   ]
  },
  {
   "title": "Pulls per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(harbor_repositories_pull_total[1d])",
     "legendFormat": "{{repo_name}}"
    }
   ]
  },
  {
   "title": "Tags per repository",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "harbor_repositories_tags_total", "legendFormat": "{{repo_name}}" }
   ]
  }
 ]
}