{
 "title": "Apache",
 "description": "Apache",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum (rate(apache_http_response_codes_total{code=~'4..|5..'}[5m])) / sum (rate(apache_http_response_codes_total[5m])))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(apache_duration_ms_total[5m])) / sum (rate(apache_accesses_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "% Workers Busy by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (apache_workers{state='busy'}) / sum (apache_workers)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Scoreboard status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (state)(apache_scoreboard)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "CPU Load by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "apache_cpuload", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Connections by State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "apache_connections", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Requests per Second by Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(apache_http_response_codes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total[5m]) /rate(apache_accesses_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Instances Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(apache_up)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Min UpTime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(apache_uptime_seconds_total)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Time since last OK request",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(time() - (apache_http_last_request_seconds{code=~'2..'}))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}