apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ntp-exporter
  labels:
    k8s-app: ntp-exporter
spec:
  selector:
    matchLabels:
      k8s-app: ntp-exporter
  template:
    metadata:
      labels:
        k8s-app: ntp-exporter
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ntp-exporter
        image: sapcc/ntp-exporter:v2.0.2
        args: [
          "-ntp.server", "Your-NTP-server"
        ]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi