{
 "title": "Kafka",
 "description": "Kafka",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Topic Size\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , topic)(kafka_log_size)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Topic Messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , topic)(kafka_topic_partition_current_offset) - sum by( , topic)(kafka_topic_partition_oldest_offset)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Topic Messages In Rate\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , topic)(rate(kafka_topic_partition_current_offset[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Top 10 Biggest Topics\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10,sum by( , topic)(kafka_log_size))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Top 10 Topics Highest Size Increase\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10,sum by( , topic)(delta(kafka_log_size[5m])))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Partition Leadership per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_partition_leader_count)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Broker Bytes In\n",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "sum (kafka_server_bytes_in)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max (kafka_controller_active_controller)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Broker Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "sum (kafka_server_bytes_out)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Broker Messages In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "sum (kafka_server_messages_in)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "ConsumerGroup Lag\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , consumergroup, topic, partition)(kafka_consumergroup_lag)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "ConsumerGroup Members\n",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , consumergroup)(kafka_consumergroup_members)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Producer Rate by User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , user)(kafka_server_producer_user_byterate)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Producer Rate by User and Client-Id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , user, client_id)(kafka_server_producer_user_client_byterate)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Consumer Rate by Client-Id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , client_id)(kafka_server_consumer_client_byterate)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Producer Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_network_producer_request_time_milliseconds{ quantile=\"0.50\"})",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum (kafka_network_producer_request_time_milliseconds{ quantile=\"0.95\"})",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Fetch Follower Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_network_fetch_follower_time_milliseconds{ quantile=\"0.50\"})",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum (kafka_network_fetch_follower_time_milliseconds{ quantile=\"0.95\"})",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Producer Rate by Client-Id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , client_id)(kafka_server_producer_client_byterate)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Producer ThrottleTime by Client-Id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , client_id)(kafka_server_producer_client_throttle_time)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Consumer ThrottleTime by Client-Id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , client_id)(kafka_server_consumer_client_throttle_time)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Producer ThrottleTime by User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , user)(kafka_server_producer_user_throttle_time)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Producer ThrottleTime by User and Client-Id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , user, client_id)(kafka_server_producer_user_client_throttle_time)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Consumer Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_network_consumer_request_time_milliseconds{ quantile=\"0.50\"})",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum (kafka_network_consumer_request_time_milliseconds{ quantile=\"0.95\"})",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "ConsumerGroup Message Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , consumergroup, topic, partition)(rate(kafka_consumergroup_current_offset[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Consumer Rate by User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , user)(kafka_server_consumer_user_byterate)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Consumer Rate by User and Client-Id\n",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , user, client_id)(kafka_server_consumer_user_client_byterate)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Consumer ThrottleTime by User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , user)(kafka_server_consumer_user_throttle_time)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Consumer ThrottleTime by User and Client-Id\n",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by( , user, client_id)(kafka_server_consumer_user_client_throttle_time)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_zookeeper_disconnections)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expired Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_zookeeper_expired_sessions)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "ZooKeeper Sync Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_zookeeper_sync_connections)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "ZooKeeper Authentication Failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_zookeeper_auth_failures)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "ZooKeeper SASL Authentications",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_zookeeper_sasl_authentications)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "ZooKeeper Read-Only Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_zookeeper_read_only_connections)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Aggregate Topic Size per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "sum (kafka_log_size)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Brokers Up\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Offline Partitions\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_controller_offline_partitions)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_under_replicated_partitions)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Under ISR Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_server_under_isr_partitions)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Brokers Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg(kafka_brokers)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Brokers Expected",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kube_workload_status_desired)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Offline Partitions\n",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_controller_offline_partitions)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions\n",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_server_under_replicated_partitions)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Under ISR Partitions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_server_under_isr_partitions)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max (kafka_controller_active_controller))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Broker Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Broker Stats" } },
  { "title": "Topic Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 }, "options": { "content": "# Topic Stats" } },
  { "title": "Consumer-Group Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 }, "options": { "content": "# Consumer-Group Stats" } },
  {
   "title": "Quota Stats",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "options": {
    "content": "Kafka has the option to enforce quotas on requests to control the Broker resources used by clients (Producers and Consumers).\n\nQuotas can be applied to user, client-id or both groups at the same time.\n\nEach client can utilize this quota per Broker before it gets throttled. Throttling means that the client will need to wait some time before being able to Produce or Consume messages again."
   }
  },
  { "title": "Network Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 }, "options": { "content": "# Network Stats" } },
  { "title": "ZooKeeper Stats", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 78 }, "options": { "content": "# ZooKeeper Stats" } }
 ]
}