apiVersion: v1
kind: RecordingRule
app: Kubernetes resources
version: 1.0.0
appVersion:
- 1.14.0
description: |
  # namespace:container_cpu_usage_seconds_total:sum_rate

  # namespace_pod_container:container_cpu_usage_seconds_total:sum_rate

  # namespace:container_cpu_usage_seconds_total:sum_rate

  # namespace:container_memory_usage_bytes:sum

  # namespace:kube_pod_container_resource_requests_memory_bytes:sum

  # namespace:kube_pod_container_resource_requests_cpu_cores:sum

  # mixin_pod_workload

  # cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile

  # cluster_quantile:scheduler_scheduling_algorithm_duration_seconds:histogram_quantile

  # cluster_quantile:scheduler_binding_duration_seconds:histogram_quantile

  # cluster_quantile:apiserver_request_duration_seconds:histogram_quantile

  # node_namespace_pod:kube_pod_info:

  # node:node_num_cpu:sum

  # node:node_cpu_utilisation:avg1m

  # node:cluster_cpu_utilisation:ratio

  # :node_cpu_saturation_load1:

  # node:node_cpu_saturation_load1:

  # :node_memory_utilisation:

  # :node_memory_MemFreeCachedBuffers_bytes:sum

  # :node_memory_MemTotal_bytes:sum

  # node:node_memory_bytes_available:sum

  # node:node_memory_bytes_total:sum

  # node:node_memory_utilisation:ratio

  # node:cluster_memory_utilisation:ratio

  # :node_memory_swap_io_bytes:sum_rate

  # node:node_memory_utilisation:

  # node:node_memory_swap_io_bytes:sum_rate

  # node:node_disk_utilisation:avg_irate

  # node:node_disk_saturation:avg_irate

  # node:node_filesystem_usage:

  # node:node_filesystem_avail:

  # :node_net_utilisation:sum_irate

  # node:node_net_utilisation:sum_irate

  # ":node_net_saturation:sum_irate

  # node:node_net_saturation:sum_irate

  # node:node_inodes_total:

  # node:node_inodes_free:
configurations:
- kind: Prometheus
  data: |
    "groups":
      - "name": "k8s.rules"
        "rules":
        - "expr": |
            sum(rate(container_cpu_usage_seconds_total{job="kubernetes-nodes-cadvisor", image!="", container!="POD"}[5m])) by (namespace)
          "record": "namespace:container_cpu_usage_seconds_total:sum_rate"
        - "expr": |
            sum by (namespace, pod, container) (
              rate(container_cpu_usage_seconds_total{job="kubernetes-nodes-cadvisor", image!="", container!="POD"}[5m])
            )
          "record": "namespace_pod_container:container_cpu_usage_seconds_total:sum_rate"
        - "expr": |
            sum(container_memory_usage_bytes{job="kubernetes-nodes-cadvisor", image!="", container!="POD"}) by (namespace)
          "record": "namespace:container_memory_usage_bytes:sum"
        - "expr": |
            sum by (namespace, label_name) (
                sum(rate(container_cpu_usage_seconds_total{job="kubernetes-nodes-cadvisor", image!="", container!="POD"}[5m])) by (namespace, pod)
              * on (namespace, pod)
                group_left(label_name) kube_pod_labels{job="kubernetes-service-endpoints"}
            )
          "record": "namespace:container_cpu_usage_seconds_total:sum_rate"
        - "expr": |
            sum by (namespace, label_name) (
                sum(container_memory_usage_bytes{job="kubernetes-nodes-cadvisor",image!="", container!="POD"}) by (pod, namespace)
              * on (namespace, pod)
                group_left(label_name) kube_pod_labels{job="kubernetes-service-endpoints"}
            )
          "record": "namespace:container_memory_usage_bytes:sum"
        - "expr": |
            sum by (namespace, label_name) (
                sum(kube_pod_container_resource_requests_memory_bytes{job="kubernetes-service-endpoints"} * on (endpoint, instance, job, namespace, pod, service) group_left(phase) (kube_pod_status_phase{phase=~"^(Pending|Running)$"} == 1)) by (namespace, pod)
              * on (namespace, pod)
                group_left(label_name) kube_pod_labels{job="kubernetes-service-endpoints"}
            )
          "record": "namespace:kube_pod_container_resource_requests_memory_bytes:sum"
        - "expr": |
            sum by (namespace, label_name) (
                sum(kube_pod_container_resource_requests_cpu_cores{job="kubernetes-service-endpoints"} * on (endpoint, instance, job, namespace, pod, service) group_left(phase) (kube_pod_status_phase{phase=~"^(Pending|Running)$"} == 1)) by (namespace, pod)
              * on (namespace, pod)
                group_left(label_name) kube_pod_labels{job="kubernetes-service-endpoints"}
            )
          "record": "namespace:kube_pod_container_resource_requests_cpu_cores:sum"
        - "expr": |
            sum(
              label_replace(
                label_replace(
                  kube_pod_owner{job="kubernetes-service-endpoints", owner_kind="ReplicaSet"},
                  "replicaset", "$1", "owner_name", "(.*)"
                ) * on(replicaset, namespace) group_left(owner_name) kube_replicaset_owner{job="kubernetes-service-endpoints"},
                "workload", "$1", "owner_name", "(.*)"
              )
            ) by (namespace, workload, pod)
          "labels":
            "workload_type": "deployment"
          "record": "mixin_pod_workload"
        - "expr": |
            sum(
              label_replace(
                kube_pod_owner{job="kubernetes-service-endpoints", owner_kind="DaemonSet"},
                "workload", "$1", "owner_name", "(.*)"
              )
            ) by (namespace, workload, pod)
          "labels":
            "workload_type": "daemonset"
          "record": "mixin_pod_workload"
        - "expr": |
            sum(
              label_replace(
                kube_pod_owner{job="kubernetes-service-endpoints", owner_kind="StatefulSet"},
                "workload", "$1", "owner_name", "(.*)"
              )
            ) by (namespace, workload, pod)
          "labels":
            "workload_type": "statefulset"
          "record": "mixin_pod_workload"
      - "name": "kube-scheduler.rules"
        "rules":
        - "expr": |
            histogram_quantile(0.99, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.99"
          "record": "cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.99, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.99"
          "record": "cluster_quantile:scheduler_scheduling_algorithm_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.99, sum(rate(scheduler_binding_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.99"
          "record": "cluster_quantile:scheduler_binding_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.9, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.9"
          "record": "cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.9, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.9"
          "record": "cluster_quantile:scheduler_scheduling_algorithm_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.9, sum(rate(scheduler_binding_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.9"
          "record": "cluster_quantile:scheduler_binding_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.5, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.5"
          "record": "cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.5, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.5"
          "record": "cluster_quantile:scheduler_scheduling_algorithm_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.5, sum(rate(scheduler_binding_duration_seconds_bucket{job="kubernetes-nodes"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.5"
          "record": "cluster_quantile:scheduler_binding_duration_seconds:histogram_quantile"
      - "name": "kube-apiserver.rules"
        "rules":
        - "expr": |
            histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job="kubernetes-apiservers"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.99"
          "record": "cluster_quantile:apiserver_request_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.9, sum(rate(apiserver_request_duration_seconds_bucket{job="kubernetes-apiservers"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.9"
          "record": "cluster_quantile:apiserver_request_duration_seconds:histogram_quantile"
        - "expr": |
            histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{job="kubernetes-apiservers"}[5m])) without(instance, pod))
          "labels":
            "quantile": "0.5"
          "record": "cluster_quantile:apiserver_request_duration_seconds:histogram_quantile"
      - "name": "node.rules"
        "rules":
        - "expr": "sum(min(kube_pod_info) by (kubernetes_node))"
          "record": ":kube_pod_info_node_count:"
        - "expr": |
            max by(kubernetes_node, namespace, pod) (label_replace(kube_pod_info{job="kubernetes-service-endpoints"}, "kubernetes_node", "$1", "node", "(.*)"))
          "record": "node_namespace_pod:kube_pod_info:"
        - "expr": |
            count by (kubernetes_node) (sum by (kubernetes_node, cpu) (
              node_cpu_seconds_total{job="kubernetes-service-endpoints"}
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            ))
          "record": "node:node_num_cpu:sum"
        - "expr": |
            1 - avg(rate(node_cpu_seconds_total{job="kubernetes-service-endpoints",mode="idle"}[1m]))
          "record": ":node_cpu_utilisation:avg1m"
        - "expr": |
            1 - avg by (kubernetes_node) (
              rate(node_cpu_seconds_total{job="kubernetes-service-endpoints",mode="idle"}[1m])
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:)
          "record": "node:node_cpu_utilisation:avg1m"
        - "expr": |
            node:node_cpu_utilisation:avg1m
              *
            node:node_num_cpu:sum
              /
            scalar(sum(node:node_num_cpu:sum))
          "record": "node:cluster_cpu_utilisation:ratio"
        - "expr": |
            sum(node_load1{job="kubernetes-service-endpoints"})
            /
            sum(node:node_num_cpu:sum)
          "record": ":node_cpu_saturation_load1:"
        - "expr": |
            sum by (kubernetes_node) (
              node_load1{job="kubernetes-service-endpoints"}
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            )
            /
            node:node_num_cpu:sum
          "record": "node:node_cpu_saturation_load1:"
        - "expr": |
            1 -
            sum(node_memory_MemFree_bytes{job="kubernetes-service-endpoints"} + node_memory_Cached_bytes{job="kubernetes-service-endpoints"} + node_memory_Buffers_bytes{job="kubernetes-service-endpoints"})
            /
            sum(node_memory_MemTotal_bytes{job="kubernetes-service-endpoints"})
          "record": ":node_memory_utilisation:"
        - "expr": |
            sum(node_memory_MemFree_bytes{job="kubernetes-service-endpoints"} + node_memory_Cached_bytes{job="kubernetes-service-endpoints"} + node_memory_Buffers_bytes{job="kubernetes-service-endpoints"})
          "record": ":node_memory_MemFreeCachedBuffers_bytes:sum"
        - "expr": |
            sum(node_memory_MemTotal_bytes{job="kubernetes-service-endpoints"})
          "record": ":node_memory_MemTotal_bytes:sum"
        - "expr": |
            sum by (kubernetes_node) (
              (node_memory_MemFree_bytes{job="kubernetes-service-endpoints"} + node_memory_Cached_bytes{job="kubernetes-service-endpoints"} + node_memory_Buffers_bytes{job="kubernetes-service-endpoints"})
              * on (namespace, pod) group_left(kubernetes_node)
                node_namespace_pod:kube_pod_info:
            )
          "record": "node:node_memory_bytes_available:sum"
        - "expr": |
            sum by (kubernetes_node) (
              node_memory_MemTotal_bytes{job="kubernetes-service-endpoints"}
              * on (namespace, pod) group_left(kubernetes_node)
                node_namespace_pod:kube_pod_info:
            )
          "record": "node:node_memory_bytes_total:sum"
        - "expr": |
            (node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum)
            /
            node:node_memory_bytes_total:sum
          "record": "node:node_memory_utilisation:ratio"
        - "expr": |
            (node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum)
            /
            scalar(sum(node:node_memory_bytes_total:sum))
          "record": "node:cluster_memory_utilisation:ratio"
        - "expr": |
            1e3 * sum(
              (rate(node_vmstat_pgpgin{job="kubernetes-service-endpoints"}[1m])
            + rate(node_vmstat_pgpgout{job="kubernetes-service-endpoints"}[1m]))
            )
          "record": ":node_memory_swap_io_bytes:sum_rate"
        - "expr": |
            1 -
            sum by (kubernetes_node) (
              (node_memory_MemFree_bytes{job="kubernetes-service-endpoints"} + node_memory_Cached_bytes{job="kubernetes-service-endpoints"} + node_memory_Buffers_bytes{job="kubernetes-service-endpoints"})
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            )
            /
            sum by (kubernetes_node) (
              node_memory_MemTotal_bytes{job="kubernetes-service-endpoints"}
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            )
          "record": "node:node_memory_utilisation:"
        - "expr": |
            1 - (node:node_memory_bytes_available:sum / node:node_memory_bytes_total:sum)
          "record": "node:node_memory_utilisation_2:"
        - "expr": |
            1e3 * sum by (kubernetes_node) (
              (rate(node_vmstat_pgpgin{job="kubernetes-service-endpoints"}[1m])
            + rate(node_vmstat_pgpgout{job="kubernetes-service-endpoints"}[1m]))
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            )
          "record": "node:node_memory_swap_io_bytes:sum_rate"
        - "expr": |
            avg(irate(node_disk_io_time_seconds_total{job="kubernetes-service-endpoints",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m]))
          "record": ":node_disk_utilisation:avg_irate"
        - "expr": |
            avg by (kubernetes_node) (
              irate(node_disk_io_time_seconds_total{job="kubernetes-service-endpoints",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m])
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            )
          "record": "node:node_disk_utilisation:avg_irate"
        - "expr": |
            avg(irate(node_disk_io_time_weighted_seconds_total{job="kubernetes-service-endpoints",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m]))
          "record": ":node_disk_saturation:avg_irate"
        - "expr": |
            avg by (kubernetes_node) (
              irate(node_disk_io_time_weighted_seconds_total{job="kubernetes-service-endpoints",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m])
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            )
          "record": "node:node_disk_saturation:avg_irate"
        - "expr": |
            max by (instance, namespace, pod, device) ((node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"}
            - node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
            / node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
          "record": "node:node_filesystem_usage:"
        - "expr": |
            max by (instance, namespace, pod, device) (node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"} / node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
          "record": "node:node_filesystem_avail:"
        - "expr": |
            sum(irate(node_network_receive_bytes_total{job="kubernetes-service-endpoints",device!~"veth.+"}[1m])) +
            sum(irate(node_network_transmit_bytes_total{job="kubernetes-service-endpoints",device!~"veth.+"}[1m]))
          "record": ":node_net_utilisation:sum_irate"
        - "expr": |
            sum by (kubernetes_node) (
              (irate(node_network_receive_bytes_total{job="kubernetes-service-endpoints",device!~"veth.+"}[1m]) +
              irate(node_network_transmit_bytes_total{job="kubernetes-service-endpoints",device!~"veth.+"}[1m]))
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            )
          "record": "node:node_net_utilisation:sum_irate"
        - "expr": |
            sum(irate(node_network_receive_drop_total{job="kubernetes-service-endpoints",device!~"veth.+"}[1m])) +
            sum(irate(node_network_transmit_drop_total{job="kubernetes-service-endpoints",device!~"veth.+"}[1m]))
          "record": ":node_net_saturation:sum_irate"
        - "expr": |
            sum by (kubernetes_node) (
              (irate(node_network_receive_drop_total{job="kubernetes-service-endpoints",device!~"veth.+"}[1m]) +
              irate(node_network_transmit_drop_total{job="kubernetes-service-endpoints",device!~"veth.+"}[1m]))
            * on (namespace, pod) group_left(kubernetes_node)
              node_namespace_pod:kube_pod_info:
            )
          "record": "node:node_net_saturation:sum_irate"
        - "expr": |
            max(
              max(
                kube_pod_info{job="kubernetes-service-endpoints", host_ip!=""}
              ) by (node, host_ip)
              * on (host_ip) group_right (kubernetes_node)
              label_replace(
                (max(node_filesystem_files{job="kubernetes-service-endpoints", mountpoint="/"}) by (instance)), "host_ip", "$1", "instance", "(.*):.*"
              )
            ) by (kubernetes_node)
          "record": "node:node_inodes_total:"
        - "expr": |
            max(
              max(
                kube_pod_info{job="kubernetes-service-endpoints", host_ip!=""}
              ) by (kubernetes_node, host_ip)
              * on (host_ip) group_right (kubernetes_node)
              label_replace(
                (max(node_filesystem_files_free{job="kubernetes-service-endpoints", mountpoint="/"}) by (instance)), "host_ip", "$1", "instance", "(.*):.*"
              )
            ) by (kubernetes_node)
          "record": "node:node_inodes_free:"
