apiVersion: v1
kind: SetupGuide
app: "sysdig-admission-controller"
version: 1.0.0
appVersion:
- latest
descriptionFile: INSTALL.md
configurations:
- name: sysdig-admission-controller-deploy.yaml
  file: include/sysdig-admission-controller-deploy.yaml