{
 "title": "ElasticSearch_Infra",
 "description": "ElasticSearch_Infra",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "elasticsearch_os_load1", "legendFormat": "{{ handler }}" },
    { "expr": "elasticsearch_os_load5", "legendFormat": "{{ handler }}" },
    { "expr": "elasticsearch_os_load15", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "JVM memory committed ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "GC time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100*(1-(elasticsearch_filesystem_data_available_bytes/elasticsearch_filesystem_data_size_bytes))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "irate(elasticsearch_transport_rx_size_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Query time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds[5m]) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total[5m]) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total[5m]) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total[5m]) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}