{
 "title": "MsSQL",
 "description": "MsSQL",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Database latency Read (LOG)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(mssql_io_st_seconds[5m])", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Database latency Write (LOG)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(mssql_io_st_seconds[5m])", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mssql_transactions_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Database latency Read (ROWS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(mssql_io_st_seconds[5m])", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Database latency Write (ROWS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(mssql_io_st_seconds[5m])", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Space used by DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (db)(mssql_disk_space_used_database_bytes_total)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Space used by table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mssql_table_used_size_bytes_total",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "mssql_buffer_cache_hit_ratio", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Connections by db",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "mssql_connections", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "up", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mssql_deadlocks", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Kill connection error",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mssql_kill_connection_errors", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mssql_memory_utilization_percentage",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mssql_buffer_cache_hit_ratio", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(mssql_connections)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Disk available",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mssql_disk_space_avaiable_bytes_total)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "% of Disk available",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mssql_disk_space_avaiable_bytes_total)/sum(mssql_disk_space_total_bytes_total) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "New Panel", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Availability" } },
  {
   "title": "New Panel (2)",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "\n✔ Check that you have **Healthy** your server.  \n\n✔ Check that **deadlocks** are low, and close to 0. If the deadlocks increase dramatically your application will receive a lot of errors from the database.\n\n✔ Also, check the connections and kill connections if you get a lot of kill connections you may have a problem.\n\n★ **Tip**: Filter by job and database to narrow down the result and identify the server with problems. "
   }
  },
  { "title": "New Panel (3)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 }, "options": { "content": "# Disk" } },
  {
   "title": "New Panel (4)",
   "type": "text",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 11 },
   "options": {
    "content": "⚑ Running **out of disk** is a general problem in databases.\n\n* ✔ Check that instance has **enough free disk**.\n * ☛ If your instance is running out of disk, you should adjust it and add more disk via PVC or manually.\n * ☛ You can select the job to study which database is using more disks than others.\n* ☛ You also can see which table is using more disk"
   }
  },
  { "title": "New Panel (5)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 }, "options": { "content": "# Latency" } },
  { "title": "New Panel (6)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 }, "options": { "content": "# Other" } },
  {
   "title": "New Panel (7)",
   "type": "text",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 41 },
   "options": {
    "content": "⚑ The **cache ratio**  should be close to 100%.\n\n⚑ The memory used could be 100% if the instance is running in Docker or Kubernetes.\n\n* ✔ Check the transaction time.\n * ☛ If the transaction time has increased or it is too high maybe you have a problem in yoursdatabase. \n"
   }
  },
  {
   "title": "New Panel (8)",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "Seeing high latency or stall in your operations may or may not be a problem but sometimes can be a problem\n\n✔  Maybe your IO system is not handling the load right\n\n✔ Maybe you are doing too much in TempDB"
   }
  }
 ]
}