{
 "title": "MySQL",
 "description": "MySQL",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Connections Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg (mysql_global_status_threads_connected) / avg (mysql_global_variables_max_connections)",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "avg (mysql_global_status_threads_running) / avg (mysql_global_variables_max_connections)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Connection Errors by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(15,rate(mysql_global_status_connection_errors_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(mysql_global_status_connection_errors_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_aborted_connects[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_aborted_clients[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL innodb log writes stalling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_log_waits[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Pool Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "((rate(mysql_global_status_innodb_buffer_pool_read_requests[5m]) - rate(mysql_global_status_innodb_buffer_pool_reads[5m])) / rate(mysql_global_status_innodb_buffer_pool_read_requests[5m])) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Pool Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mysql_global_status_buffer_pool_pages / mysql_global_status_buffer_pool_pages",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Open Files Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_open_files / mysql_global_variables_open_files_limit",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Table Open Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits[5m]) / (rate(mysql_global_status_table_open_cache_hits[5m]) + rate(mysql_global_status_table_open_cache_misses[5m])))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Sorts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_sort_rows[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_sort_range[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_sort_merge_passes[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_sort_scan[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_table_locks_immediate[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_table_locks_waited[5m]) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_select_full_join[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_select_full_range_join[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_sort_merge_passes[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_select_range_check[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_select_scan[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Questions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mysql_global_variables_thread_cache_size",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_status_threads_cached",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_threads_created[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_page_size",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_variables_query_cache_size",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_variables_tokudb_cache_size",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "mysql_global_variables_tokudb_cache_size",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, rate(mysql_global_status_commands_total[5m])>0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "# Servers Running",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(mysql_up==1)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Min. Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(mysql_global_status_uptime)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "# Servers Down",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(mysql_up==0) or vector(0)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "New Panel",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "If there are connection errors in an instance, you can identify first the type of error in the first panel. \n\nIf the error is related to the number of **maximum connections reached**, you can inspect the second panel to evaluate the usage of connections. \n- ☛ Typically, the usage of open connections should be under 80% and the running connections under 60%\n\n⚠ Beware that **increasing the max number of connections will affect the number of open files** that the system keeps open. To see the usage of open files, consult the panel below. "
   }
  },
  {
   "title": "New Panel (2)",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "For the correct tuning of the performance of the MySQL database, it is important to correctly adjust the cache to the use of the database. \n- ☛ **Degraded performance can be detected with the Slow Queries log**.\n\nTo increase the performance of the database, MySQL offers Cache. \n* A **high hit ratio will make queries faster** but increasing the pool size is not trivial. \n* Before **increasing the cache size to improve the cache hit ratio** , you need to take into account the available memory and open files. \n* Also, an **infra-utilized cache** can be a sign of oversized memory in the node. \n \n⚠ Beware that **increasing the table open cache will affect the number of open files** that the system keeps open. To see the usage of open files, consult the panel below. "
   }
  },
  {
   "title": "New Panel (3)",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "options": {
    "content": "Here you will find information on: \n* How the database is using network traffic and the split-up of the usage of memory. This can help you evaluate the need to **increase network bandwidth or memory in your node**. \n* The kind of *select* and *sort* queries that may affect the response time of the database. The **high usage of non-optimized queries can cause high response time**. "
   }
  }
 ]
}