{
 "title": "Kubernetes / Scheduler",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(kubelet_running_pod_count:kubernetes_nodes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    { "expr": "sum(up:kube_scheduler)" }
   ]
  },
  {
   "title": "Scheduling Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scheduler_e2e_scheduling_duration_seconds_count:kube_scheduler[5m])) by (instance)",
     "legendFormat": "{{instance}} e2e"
    },
    {
     "expr": "sum(rate(scheduler_binding_duration_seconds_count:kube_scheduler[5m])) by (instance)",
     "legendFormat": "{{instance}} binding"
    },
    {
     "expr": "sum(rate(scheduler_scheduling_algorithm_duration_seconds_count:kube_scheduler[5m])) by (instance)",
     "legendFormat": "{{instance}} scheduling algorithm"
    },
    {
     "expr": "sum(rate(scheduler_volume_scheduling_duration_seconds_count:kube_scheduler[5m])) by (instance)",
     "legendFormat": "{{instance}} volume"
    }
   ]
  },
  {
   "title": "Scheduling latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scheduler_volume_scheduling_duration_seconds_count:kube_scheduler",
     "legendFormat": "{{instance}} e2e"
    },
    {
     "expr": "scheduler_binding_duration_seconds_bucket:kube_scheduler",
     "legendFormat": "{{instance}} binding"
    },
    {
     "expr": "scheduler_scheduling_algorithm_duration_seconds_bucket:kube_scheduler",
     "legendFormat": "{{instance}} scheduling algorithm"
    },
    {
     "expr": "scheduler_volume_scheduling_duration_seconds_bucket:kube_scheduler",
     "legendFormat": "{{instance}} volume"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total:kube_scheduler{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kube_scheduler{code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kube_scheduler{code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total:kube_scheduler{code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rest_client_request_latency_seconds_bucket:kubernetes_control_manager:post",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rest_client_request_latency_seconds_bucket:kubernetes_control_manager:get",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes:kube_scheduler",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total:kube_scheduler[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines:kube_scheduler", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}