repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: prometheus-controlplane
    namespace: monitoring
    chart: prometheus-community/prometheus
    atomic: true
    values:
      - prometheus.yml.gotmpl
