apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
  namespace: agent
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus' # config for federation
      honor_labels: true
      metrics_path: '/federate'
      metric_relabel_configs:
      - regex: 'kubernetes_pod_name'
        action: labeldrop
      params:
        'match[]':
          - '{sysdig="true"}'
      sysdig_sd_configs:
      - tags:
          namespace: monitoring
          deployment: prometheus-server
  dragent.yaml: |-
    metrics_excess_log: true
    use_promscrape: true
    prometheus:
      enabled: true
      process_filter:
        - exclude:
            process.name: docker-proxy
        - exclude:
            container.image: sysdig/agent
        # special rule to exclude processes matching configured prometheus appcheck
        - exclude:
            appcheck.match: prometheus
        - include:
            container.label.io.prometheus.scrape: "true"
            conf:
                # Custom path definition
                # If the label doesn't exist we'll still use "/metrics"
                path: "{container.label.io.prometheus.path}"
      
                # Port definition
                # - If the label exists, only scan the given port.
                # - If it doesn't, use port_filter instead.
                # - If there is no port_filter defined, skip this process
                port: "{container.label.io.prometheus.port}"
                port_filter:
                    - exclude: [9092,9200,9300]
                    - include: 9090-9500
                    - include: [9913,9984,24231,42004]
        - exclude:
            container.label.io.prometheus.scrape: "false"
        - include:
            kubernetes.pod.annotation.prometheus.io/scrape: true
            kubernetes.pod.annotation.prometheus.io/scheme: "https"
            conf:
                use_https: true
                path: "{kubernetes.pod.annotation.prometheus.io/path}"
                port: "{kubernetes.pod.annotation.prometheus.io/port}"
        - include:
            kubernetes.pod.annotation.prometheus.io/scrape: true
            conf:
                path: "{kubernetes.pod.annotation.prometheus.io/path}"
                port: "{kubernetes.pod.annotation.prometheus.io/port}"
        - exclude:
            kubernetes.pod.annotation.prometheus.io/scrape: false