{
 "title": "AWS ELB Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Latency",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Error Rate From the Load Balancer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "aws_elb_error_rate_4_xx_from_elb_count_sum",
     "legendFormat": "4XX"
    },
    {
     "expr": "aws_elb_error_rate_5_xx_from_elb_count_sum",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Error Rate From the Backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "aws_elb_error_rate_4_xx_from_backend_count_sum",
     "legendFormat": "4XX"
    },
    {
     "expr": "aws_elb_error_rate_5_xx_from_backend_count_sum",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Top P95 Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "topk(5,aws_elb_latency_p95)", "legendFormat": "{{dimension_LoadBalancerName}}" }
   ]
  },
  {
   "title": "Unhealthy Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_un_healthy_host_count_minimum)",
     "legendFormat": "Unhealthy Hosts"
    }
   ]
  },
  {
   "title": "Queue Spillovers Rejections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_spillover_count_sum or vector(0))",
     "legendFormat": "Spillovers"
    }
   ]
  },
  {
   "title": "Top P95 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "topk(5,aws_elb_latency_p95)", "legendFormat": "{{dimension_LoadBalancerName}}" }
   ]
  },
  {
   "title": "Saturation",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Top Surge Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_elb_surge_queue_length_maximum)",
     "legendFormat": "{{dimension_LoadBalancerName}}"
    }
   ]
  },
  {
   "title": "Top Surge Queue Length",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(5,aws_elb_surge_queue_length_maximum)",
     "legendFormat": "{{dimension_LoadBalancerName}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Load Balancers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "count(aws_elb_info)" }
   ]
  },
  {
   "title": "Requests/sec With 2XX and 3XX Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_httpcode_backend_2_xx_count_sum or vector(0)) / 300",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(aws_elb_httpcode_backend_3_xx_count_sum or vector(0)) / 300",
     "legendFormat": "3XX"
    }
   ]
  },
  {
   "title": "Top Requests / Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_elb_request_count_sum / 300)",
     "legendFormat": "{{dimension_LoadBalancerName}}"
    }
   ]
  },
  {
   "title": "Total Requests / Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_request_count_sum)/  300",
     "legendFormat": "{{dimension_LoadBalancerName}}"
    }
   ]
  },
  {
   "title": "Top Healthy Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_elb_healthy_host_count_sum)",
     "legendFormat": "{{dimension_LoadBalancerName}}"
    }
   ]
  },
  {
   "title": "Total Healthy Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_healthy_host_count_sum)",
     "legendFormat": "Total Healthy Hosts"
    }
   ]
  }
 ]
}