{
 "title": "Rabbitmq_Overview",
 "description": "Rabbitmq_Overview",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory available before publishers blocked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(rabbitmq_resident_memory_limit_bytes ) -(rabbitmq_process_resident_memory_bytes)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk space available before publishers blocked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rabbitmq_disk_space_available_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "File descriptors available",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(rabbitmq_process_max_fds) -(rabbitmq_process_open_fds )",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "TCP sockets available",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(rabbitmq_process_max_tcp_sockets ) -(rabbitmq_process_open_tcp_sockets)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Messages ready to be delivered to consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Messages pending consumer acknowledgement",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Ready messages",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Publishers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels) - sum(rabbitmq_channel_consumers)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(rabbitmq_connections)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Queues",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(rabbitmq_queues)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Unacknowledged messages",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total[5m])) +sum(rate(rabbitmq_channel_messages_delivered_total[5m])) +sum(rate(rabbitmq_channel_messages_delivered_ack_total[5m])) +sum(rate(rabbitmq_channel_get_total[5m])) +sum(rate(rabbitmq_channel_get_ack_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_consumers)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(rabbitmq_channels)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Nodes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(rabbitmq_build_info)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Messages Unroutable Dropped",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_messages_unroutable_dropped_total)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Messages Unroutable Returned",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_messages_unroutable_dropped_total)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Nodes (2)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 }, "options": { "content": "# RABBITMQ NODES (PODS)" } },
  { "title": "Nodes (3)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 }, "options": { "content": "# QUEUED MESSAGES" } }
 ]
}