apiVersion: v1
kind: Alert
app: ''
version: 1.0.0
appVersion:
- 1.0.0
configurations:
- kind: Prometheus
  data: |
    - alert:
      expr:
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Text {{$labels.label}}
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": null,
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": null,
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
descriptionFile: ALERTS.md
