{
 "title": "Cassandra",
 "description": "Cassandra dashboard for cassandra exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(sysdig_container_info,cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up:cassandra * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "ClientRead avg duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(cassandra_client_request_latency_seconds:cassandra{operation=\"read\"}* on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "ClientWrite avg duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(cassandra_client_request_latency_seconds:cassandra{operation=\"write\"}* on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(cassandra_jvm_memory_pool_used_bytes:cassandra{type=\"HEAP\"} * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster) / sum(cassandra_jvm_memory_pool_maximum_bytes:cassandra{type=\"HEAP\"}* on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)) * 100\n"
    }
   ]
  },
  {
   "title": "Pending compactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_table_estimated_pending_compactions:cassandra * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)\n"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_commit_log_pending_tasks:cassandra * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)\n"
    }
   ]
  },
  {
   "title": "Unavailable exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_client_request_unavailable_exceptions_total:cassandra[5m]) * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)\n"
    }
   ]
  },
  {
   "title": "Available disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(cassandra_storage_filesystem_usable_bytes:cassandra* on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)/sum(cassandra_storage_filesystem_bytes_total:cassandra* on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}) by (cluster)) * 100"
    }
   ]
  },
  {
   "title": "95thPercentile read latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_request_latency_seconds:cassandra{quantile=\"0.95\", operation=\"read\"} * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}",
     "legendFormat": "{{consistency}} {{instance}}"
    }
   ]
  },
  {
   "title": "95thPercentile write latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_request_latency_seconds:cassandra{quantile=\"0.95\", operation=\"write\"} * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}",
     "legendFormat": "{{consistency}} {{instance}}"
    }
   ]
  },
  {
   "title": "Avaiable disk by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_filesystem_usable_bytes:cassandra * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Users conected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_native_connections:cassandra * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU load ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_os_1m_load_average:cassandra * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_os_free_memory_bytes:cassandra * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}",
     "legendFormat": "Memory free - {{instance}}"
    },
    {
     "expr": "cassandra_os_memory_bytes_total:cassandra * on (container_id) group_left(cluster,namespace,pod) sysdig_container_info{cluster=~\"$cluster\"}",
     "legendFormat": "Memory total - {{instance}}"
    }
   ]
  }
 ]
}