repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com/
releases:  
  - name: prometheus-cassandra
    namespace: cassandra
    chart: stable/prometheus
    atomic: true
    values:
      - prometheus.yml.gotmpl