{
 "title": "HAProxy OC Service Golden Signals",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(haproxy_server_up,service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (server,pod,service)(haproxy_server_up{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "HTTP Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(haproxy_server_http_responses_total{service=~\"$service\",code!=\"2xx\"}[$__interval])) / sum  by (pod) (rate(haproxy_server_http_responses_total{service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Check Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (pod, service)(rate(haproxy_server_check_failures_total{service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{service}} > {{pod}}"
    }
   ]
  },
  {
   "title": "Downtime By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (pod,service)(rate(haproxy_server_downtime_seconds_total{service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{service}} > {{pod}}"
    }
   ]
  },
  {
   "title": "Connection Errors by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (pod,service)(rate(haproxy_server_connection_errors_total{service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{service}} > {{pod}}"
    }
   ]
  },
  {
   "title": "Average response latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (service)(haproxy_server_http_average_response_latency_milliseconds{service=~\"$service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(haproxy_server_current_queue{service=~\"$service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_connections_total{service=~\"$service\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Responses OK",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(service,pod)(rate(haproxy_server_http_responses_total{code=\"2xx\",service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{service}} > {{pod}}"
    }
   ]
  },
  {
   "title": "Bytes Inbound",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (service,pod)(rate(haproxy_server_bytes_in_total{service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{service}} > {{pod}}"
    }
   ]
  },
  {
   "title": "Bytes Outbound",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (service,pod)(rate(haproxy_server_bytes_out_total{service=~\"$service\"}[$__interval]))",
     "legendFormat": "{{service}} > {{pod}}"
    }
   ]
  }
 ]
}