{
 "title": "HAProxy OC Ingress Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(time() - haproxy_process_start_time_seconds))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(haproxy_process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Backends OK",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg by (route)(haproxy_backend_up{route!=\"\"})"
    }
   ]
  },
  {
   "title": "Response Errors rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_responses_total{code=~\"4xx|5xx\"}[$__interval]) / rate(haproxy_frontend_http_responses_total[$__interval])",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Down Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_downtime_seconds_total[$__interval])"
    }
   ]
  },
  {
   "title": "Connections error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_connections_total[$__interval]) - rate(haproxy_server_connection_errors_total[$__interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Failed health checks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_check_failures_total[$__interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Current Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(haproxy_server_current_queue{server!=\"\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Avg Response Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (route)(haproxy_server_http_average_response_latency_milliseconds{service!=\"\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Frontend sessions rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (haproxy_frontend_current_sessions)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_process_cpu_seconds_total[$__interval])",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "haproxy_process_resident_memory_bytes",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "haproxy_process_virtual_memory_bytes",
     "legendFormat": "{{container_id}}"
    }
   ]
  },
  {
   "title": "Max open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "haproxy_process_max_fds", "legendFormat": "{{container_id}}" }
   ]
  },
  {
   "title": "Frontend Bytes In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (rate(haproxy_frontend_bytes_in_total[$__interval]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (rate(haproxy_frontend_connections_total[$__interval]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Frontend Bytes Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend) (rate(haproxy_frontend_bytes_out_total[$__interval]))",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Frontend HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (frontend,code) (rate(haproxy_frontend_http_responses_total[$__interval]))",
     "legendFormat": "{{frontend}}: {{code}}"
    }
   ]
  }
 ]
}