groups:
    - name: OpenShift-HAProxy-Router
      rules:
        - alert: '[OpenShift-HAProxy-Router] Router Down'
          expr: |
            absent(haproxy_process_start_time_seconds) == 1
          for: 10m
          labels:
            severity: critical
          annotations:
            description: Router HAProxy down. No instances running.
        - alert: '[OpenShift-HAProxy-Router] HAProxy Down'
          expr: |
            haproxy_up == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            description: HAProxy down on a pod.
        - alert: '[OpenShift-HAProxy-Router] HAProxy Reload Failure'
          expr: |
            template_r_reload_failure == 1
          for: 10m
          labels:
            severity: info
          annotations:
            description: HAProxy reloads are failing. New configurations will not be applied.
        - alert: '[OpenShift-HAProxy-Router] Percentage of routers low'
          expr: |
            count (haproxy_process_start_time_seconds)/sum (kube_workload_status_desired) < 0.75
          for: 10m
          labels:
            severity: critical
          annotations:
            description: Less than 75% Routers are up.
        - alert: '[OpenShift-HAProxy-Router] Route Down'
          expr: |
            sum (haproxy_server_up) < 1
          for: 10m
          labels:
            severity: critical
          annotations:
            description: This alert detects if all servers are down in a route
        - alert: '[OpenShift-HAProxy-Router] High Latency'
          expr: |
            max (haproxy_server_http_average_response_latency_milliseconds) > 250
          for: 10m
          labels:
            severity: warning
          annotations:
            description: This alert detects high latency in at least one server of the route.
        - alert: '[OpenShift-HAProxy-Router] Pod Health Check Failure'
          expr: |
            sum (rate(haproxy_server_check_failures_total[5m])) > 0
          for: 10m
          labels:
            severity: critical
          annotations:
            description: This alert triggers when there is a recurrent pod health check failure.
        - alert: '[OpenShift-HAProxy-Router] Queue not empty in route'
          expr: |
            sum (haproxy_server_current_queue) > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            description: This alert triggers when a queue is not empty in a route.
        - alert: '[OpenShift-HAProxy-Router] High error rate in route'
          expr: |
            sum (rate(haproxy_server_http_responses_total{code!="2xx"}[5m])) /sum (rate(haproxy_server_http_responses_total[5m]))> 0.15
          for: 10m
          labels:
            severity: critical
          annotations:
            description: This alert triggers when the error rate in a route is higher than 15%.
        - alert: '[OpenShift-HAProxy-Router] Connection errors in route'
          expr: |
            sum (rate(haproxy_server_connection_errors_total[5m])) > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            description: This alert triggers when there are recurring connection errors in a route.
