{
 "title": "ElasticSearch infra",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(elasticsearch_indices_docs,cluster)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},name)"
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_load1{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load1: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load5{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load5: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load15{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load15: {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} committed: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit", "label": "Disk Usage %" }
   ],
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}/elasticsearch_filesystem_data_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: sent "
    },
    {
     "expr": "-irate(elasticsearch_transport_rx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}