apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-exporter
  name: elasticsearch-exporter
  namespace: sysdigcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        promcat.sysdig.com/port: "9108"
        promcat.sysdig.com/target_ns: elastic-namespace
        promcat.sysdig.com/target_workload_type: statefulset
        promcat.sysdig.com/target_workload_name: elasticsearch
        promcat.sysdig.com/integration_type: elasticsearch
      labels:
        app: elasticsearch-exporter
    spec:
      containers:
      - command:
        - elasticsearch_exporter
        - --es.all
        - --es.indices
        - --es.indices_settings
        - --es.shards
        - --es.snapshots
        - --es.cluster_settings
        - --es.timeout=60s
        - --es.ssl-skip-verify
        - --es.ca=/usr/share/elasticsearch/config/certs/root-ca.pem
        - --web.listen-address=:9108
        - --web.telemetry-path=/metrics
        env:
          - name: ELASTIC_USER
            valueFrom:
              configMapKeyRef:
                key: elasticsearch.adminuser
                name: sysdigcloud-config
          - name: ES_URI
            value: https://$(ELASTIC_USER):$(ELASTICSEARCH_ADMIN_PASSWORD)@sysdigcloud-elasticsearch:9200
        envFrom:
        - secretRef:
            name: elasticsearch-tls
        image: quay.io/sysdig/elasticsearch-exporter:1.2.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - sleep 20
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: elasticsearch-exporter
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/certs/
          name: elasticsearch-tls-certs      
        ports:
        - containerPort: 9108
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      volumes:
      - name: elasticsearch-tls-certs
        secret:
          defaultMode: 256
          secretName: es-certs