apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  selector:
    matchLabels:
      app: nginx-A
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-A
      annotations:
        promcat.sysdig.com/integration_type: nginx
        promcat.sysdig.com/port: "9113"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
      - name: nginx-exporter
        image: quay.io/sysdig/nginx-exporter:latest
        args:
          - "-nginx.scrape-uri=http://localhost:80/nginx_status"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9113
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-config
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;
      location / {
          proxy_pass http://traffic-mirror:8080;
      }
      location /nginx_status {
        stub_status on;
        access_log  on;
        allow all;  # REPLACE with your access policy
      }
    }