{
 "title": "Nginx App Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "query": "label_values(nginx_up,app)" }
  ]
 },
 "panels": [
  {
   "title": "Instances Up",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(nginx_up{app='$app'} or vector(0))"
    }
   ]
  },
  {
   "title": "HTTP Request per instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{app='$app'}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waiting connections per instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_waiting{app='$app'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Not Handled connections per instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(rate(nginx_connections_accepted{app='$app'}[5m])) - (rate(nginx_connections_handled{app='$app'}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active, reading and writing connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_connections_active{app='$app'})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(nginx_connections_reading{app='$app'})",
     "legendFormat": "Reading"
    },
    {
     "expr": "sum(nginx_connections_writing{app='$app'})",
     "legendFormat": "Writing"
    }
   ]
  },
  {
   "title": "Accepted and handled connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted{app='$app'}[5m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(rate(nginx_connections_handled{app='$app'}[5m]))",
     "legendFormat": "Handled"
    }
   ]
  }
 ]
}