---
apiVersion: v1
kind: App
name: "Docker"
keywords: 
  - Containers
  - Coming soon
availableVersions: 
  - '18.09.9'
shortDescription: "Docker container engine"
description: |
  Docker Engine powers millions of applications worldwide, providing a standardized packaging format for diverse applications.
  Docker Engine is the industry’s de facto container runtime that runs on various Linux (CentOS, Debian, Fedora, Oracle Linux, RHEL, SUSE, and Ubuntu) and Windows Server operating systems. Docker creates simple tooling and a universal packaging approach that bundles up all application dependencies inside a container which is then run on Docker Engine. Docker Engine enables containerized applications to run anywhere consistently on any infrastructure, solving “dependency hell” for developers and operations teams, and eliminating the “it works on my laptop!” problem.
icon: https://upload.wikimedia.org/wikipedia/commons/4/4e/Docker_%28container_engine%29_logo.svg
website: https://www.docker.com/
available: true