---
apiVersion: v1
kind: App
name: "Harbor"
keywords: 
  - registry
  - available
availableVersions: 
  - 1.10
shortDescription: "Harbor is an open source container image registry that secures images with role-based access control"
description: |
  Harbor is an open source container image registry that secures images with role-based access control, scans images for vulnerabilities, and signs images as trusted.
  As a CNCF Incubating project, Harbor delivers compliance, performance, and interoperability to help you consistently and securely manage images across cloud native 
  compute platforms like Kubernetes and Docker.
icon: https://goharbor.io/img/logos/harbor-horizontal-color.png
website: https://goharbor.io/
available: true