---
apiVersion: v1
kind: App
name: "kafka"
keywords: 
  - Message-broker
  - Available
availableVersions: 
  - 'latest'
shortDescription: "Apache Kafka is an open-source stream-processing software platform."
description: |
  Apache Kafka is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.
icon: https://raw.githubusercontent.com/sysdiglabs/promcat-resources/master/apps/images/kafka.png
website: https://kafka.apache.org/
available: true