---
apiVersion: v1
kind: App
name: "mysql"
keywords: 
  - Database
  - Available
availableVersions: 
  - 'latest'
shortDescription: "MySQL is an open-source relational database management system (RDBMS)"
description: |
  MySQL is an open-source relational database management system (RDBMS)
icon: https://raw.githubusercontent.com/sysdiglabs/promcat-resources/master/apps/images/MySQL.png
website: https://dev.mysql.com/
available: true