---
apiVersion: v1
kind: App
name: "nginx"
keywords: 
  - web-server
  - coming soon
availableVersions: 
  - 1.17
shortDescription: "The open source web server that powers 400 million websites."
description: |
  The open source web server that powers 400 million websites.
icon: https://upload.wikimedia.org/wikipedia/commons/c/c5/Nginx_logo.svg
website: https://nginx.org/
available: false