---
apiVersion: v1
kind: App
name: "ntp"
keywords: 
  - Network
  - Available
availableVersions: 
  - 'latest'
shortDescription: "The Network Time Protocol (NTP) is a networking protocol for clock synchronization between computer systems"
description: |
  The Network Time Protocol (NTP) is a networking protocol for clock synchronization between computer systems over packet-switched, variable-latency data networks. In operation since before 1985, NTP is one of the oldest Internet protocols in current use. NTP was designed by David L. Mills of the University of Delaware.
icon: https://raw.githubusercontent.com/sysdiglabs/promcat-resources/master/apps/images/ntp.png
website: http://www.ntp.org/
available: yes