{
 "title": "Windows_Node_Overview_Legacy",
 "description": "Windows_Node_Overview_Legacy",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage by Mode",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * avg by (mode) (rate(wmi_cpu_time_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "CPU Usage by Core",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * sum by (core) (rate(wmi_cpu_time_total{mode != 'idle'}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100* (wmi_cs_physical_memory_bytes - wmi_os_physical_memory_free_bytes) / wmi_cs_physical_memory_bytes",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "100 * (wmi_os_virtual_memory_bytes - wmi_os_virtual_memory_free_bytes) / wmi_os_virtual_memory_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "wmi_os_physical_memory_free_bytes",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "wmi_os_virtual_memory_free_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk Usage by Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * (wmi_logical_disk_size_bytes - wmi_logical_disk_free_bytes) / wmi_logical_disk_size_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Free Disk by Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "wmi_logical_disk_free_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Disk Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_writes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_reads_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_read_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_write_bytes_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk Reqs. Queued",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "wmi_logical_disk_requests_queued",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Disk ops Splitted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_logical_disk_split_ios_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Inbound Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * rate(wmi_net_packets_received_errors[5m]) / (rate(wmi_net_packets_received_errors[5m]) + rate(wmi_net_packets_received_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Outbound Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * rate(wmi_net_packets_outbound_errors[5m]) / (rate(wmi_net_packets_outbound_errors[5m]) + rate(wmi_net_packets_sent_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Inbound Discard Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * rate(wmi_net_packets_received_discarded[5m]) / (rate(wmi_net_packets_received_discarded[5m]) + rate(wmi_net_packets_received_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Outbound Discard Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * rate(wmi_net_packets_outbound_discarded[5m]) / (rate(wmi_net_packets_outbound_discarded[5m]) + rate(wmi_net_packets_sent_total[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Bandwidth Usage by Interface",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * (rate(wmi_net_bytes_total[5m])) * 8 / wmi_net_current_bandwidth",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Bandwidth Free by Interface",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "wmi_net_current_bandwidth - ((rate(wmi_net_bytes_total[5m])) * 8) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Received IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_net_packets_received_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Sent IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_net_packets_sent_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Received Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_net_bytes_received_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Network Sent Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_net_bytes_sent_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Processes and Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "wmi_os_processes", "legendFormat": "{{ handler }}" },
    { "expr": "wmi_system_threads", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Processor Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "wmi_system_processor_queue_length",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Pagination Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * (wmi_os_paging_limit_bytes - wmi_os_paging_free_bytes) / wmi_os_paging_limit_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "User Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "wmi_os_users", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(wmi_system_context_switches_total[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Free Pagination",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "wmi_os_paging_free_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Physical Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 * (wmi_cs_physical_memory_bytes - wmi_os_physical_memory_free_bytes) / wmi_cs_physical_memory_bytes",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 * sum(rate(wmi_cpu_time_total{mode != 'idle'}[5m])) / count(wmi_cpu_core_frequency_mhz)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(wmi_cpu_core_frequency_mhz)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "wmi_cs_physical_memory_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Up Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(time() - wmi_system_system_up_time) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "wmi_system_threads", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Processes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "wmi_os_processes", "legendFormat": "{{ handler }}" }
   ]
  }
 ]
}