{
 "title": "OPA Gatekeeper",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Up Gatekeeper",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{gatekeeper_sh_system=\"yes\"})"
    }
   ]
  },
  {
   "title": "Time since last audit",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-gatekeeper_audit_last_run_time"
    }
   ]
  },
  {
   "title": "Requests rate routed to webhook",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(gatekeeper_request_count[$__interval])",
     "legendFormat": "{{admission_status}}"
    }
   ]
  },
  {
   "title": "Latency of Gatekeeper per action",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(gatekeeper_request_duration_seconds_bucket[$__interval]))",
     "legendFormat": "{{admission_status}} p99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(gatekeeper_request_duration_seconds_bucket[$__interval]))",
     "legendFormat": "{{admission_status}} p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(gatekeeper_request_duration_seconds_bucket[$__interval]))",
     "legendFormat": "{{admission_status}} p50"
    }
   ]
  },
  {
   "title": "Violations rate per constraint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(gatekeeper_violations[$__interval])",
     "legendFormat": "{{enforcement_action}}"
    }
   ]
  },
  {
   "title": "Current number of known constraints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gatekeeper_constraints",
     "legendFormat": "{{enforcement_action}} > {{status}}"
    }
   ]
  },
  {
   "title": "Observed constraint templates rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(gatekeeper_constraint_templates[$__interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency of audit operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(gatekeeper_audit_duration_seconds_bucket[$__interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, rate(gatekeeper_audit_duration_seconds_bucket[$__interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(gatekeeper_audit_duration_seconds_bucket[$__interval]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Constraint template ingestion actions rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(gatekeeper_constraint_template_ingestion_count[$__interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency of constraint template ingestion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(gatekeeper_constraint_template_ingestion_duration_seconds_bucket[$__interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, rate(gatekeeper_constraint_template_ingestion_duration_seconds_bucket[$__interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(gatekeeper_constraint_template_ingestion_duration_seconds_bucket[$__interval]))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}