{
 "title": "[Promcat.io] Nginx Overview",
 "description": "NGINX_App_Overview",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Instances Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (nginx_up or vector(0))", "legendFormat": "Instances up" }
   ]
  },
  {
   "title": "Instances Up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum (nginx_up or vector(0))", "legendFormat": "Instances up" }
   ]
  },
  {
   "title": "Active, reading and writing connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (nginx_connections_active )",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "sum (nginx_connections_reading)",
     "legendFormat": "Reading Connections"
    },
    {
     "expr": "sum (nginx_connections_writing)",
     "legendFormat": "Writing Connections"
    }
   ]
  },
  {
   "title": "Accepted and handled connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nginx_connections_accepted[5m]))",
     "legendFormat": "Accepted Connections"
    },
    {
     "expr": "sum(rate(nginx_connections_handled[5m]))",
     "legendFormat": "Handled Connections"
    }
   ]
  },
  {
   "title": "Waiting connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Not Handled connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[5m]) - rate(nginx_connections_handled[5m]) > 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}