apiVersion: v1
kind: Namespace
metadata:
  name: yace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace-alb
  namespace: yace
spec:
  selector:
    matchLabels:
      app: yace-alb
  replicas: 1
  template:
    metadata:
      labels:
        app: yace-alb
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: yace
        image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.18.0-alpha
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: yace-alb-config
            mountPath: /tmp/config.yml
            subPath: config.yml
          - name: yace-alb-credentials
            mountPath: /exporter/.aws/credentials
            subPath: credentials
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            name: yace-alb-config
          name: yace-alb-config
        - secret:
            defaultMode: 420
            secretName: yace-alb-credentials
          name: yace-alb-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-alb-config
  namespace: yace
data:
  config.yml: |
    discovery:
      jobs:
      - regions: 
        - us-east-1
        type: alb
        metrics:
          - name: ActiveConnectionCount
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: ClientTLSNegotiationErrorCount
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: ConsumedLCUs
            statistics:
            - Sum
            period: 300
            length: 3600

          - name: HTTP_Fixed_Response_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTP_Redirect_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTP_Redirect_Url_Limit_Exceeded_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_3XX_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_4XX_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_5XX_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_500_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_502_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_503_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_504_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: IPv6ProcessedBytes
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: IPv6RequestCount
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: NewConnectionCount
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: ProcessedBytes
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: RejectedConnectionCount
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: RequestCount
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: RuleEvaluations
            statistics:
            - Sum
            period: 300
            length: 3600

          #- name: LambdaTargetProcessedBytes
          #  statistics:
          #  - Sum
          #  period: 300
          #  length: 3600

          - name: ELBAuthError
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: ELBAuthFailure
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: ELBAuthLatency
            statistics:
            - Average
            period: 300
            length: 3600
          - name: ELBAuthRefreshTokenSuccess
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: ELBAuthSuccess
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: ELBAuthUserClaimsSizeExceeded
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
      - regions: 
        - us-east-1
        type: alb
        awsDimensions:
          - AvailabilityZone
        metrics:
          - name: DroppedInvalidHeaderRequestCount
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: ForwardedInvalidHeaderRequestCount
            statistics:
            - Sum
            period: 300
            length: 3600
      - regions: 
        - us-east-1
        type: alb
        awsDimensions:
          - TargetGroup
        metrics:
          - name: HealthyHostCount
            statistics:
            - Average
            period: 300
            length: 3600
          - name: HTTPCode_Target_2XX_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_Target_3XX_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_Target_4XX_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_Target_5XX_Count
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: NonStickyRequestCount
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: RequestCountPerTarget
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: TargetConnectionErrorCount
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: TargetResponseTime
            statistics:
            - p95
            period: 300
            length: 3600
          - name: TargetTLSNegotiationErrorCount
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: UnHealthyHostCount
            statistics:
            - Average
            period: 300
            length: 3600
          #- name: LambdaInternalError
          #  statistics:
          #  - Sum
          #  period: 300
          #  length: 3600
          #  nilToZero: true
          #- name: LambdaUserError
          #  statistics:
          #  - Sum
          #  period: 300
          #  length: 3600
          #  nilToZero: true
---
apiVersion: v1
kind: Secret
metadata:
  name: yace-alb-credentials
  namespace: yace
data:
  # Add in credentials the result of:
  # cat ~/.aws/credentials | base64
  credentials: |
    XXXXX
