{
 "title": "AWS ALB Golden Signals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Errors", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }, "content": "\n\n\n" },
  { "title": "Latency", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }, "content": "\n\n\n" },
  {
   "title": "Errors From the Load Balancer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_httpcode_elb_4_xx_count_sum)",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(aws_alb_httpcode_elb_5_xx_count_sum)",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Errors From the Target Groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_tg_httpcode_target_4_xx_count_sum)",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(aws_alb_tg_httpcode_target_5_xx_count_sum)",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Top 5 Response Time Target Groups",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(5,aws_alb_tg_target_response_time_p95)",
     "legendFormat": "{{dimension_TargetGroup}}"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_tg_un_healthy_host_count_average)",
     "legendFormat": "Unhealthy hots"
    }
   ]
  },
  {
   "title": "TLS Negotiation Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_client_tls_negotiation_error_count_sum)",
     "legendFormat": "TLS negotiation error"
    }
   ]
  },
  {
   "title": "P95 Target Groups Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5,aws_alb_tg_target_response_time_p95)",
     "legendFormat": "{{dimension_LoadBalancer}} - {{dimension_TargetGroup}}"
    }
   ]
  },
  { "title": "Saturation", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "content": "\n\n\n" },
  {
   "title": "Rejected Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_rejected_connection_count_sum)",
     "legendFormat": "rejected requests"
    }
   ]
  },
  {
   "title": "Top 5  Load Balancers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "aws_alb_processed_bytes_sum", "legendFormat": "{{dimension_LoadBalancer}}" }
   ]
  },
  { "title": "Utilization", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "content": "\n\n\n" },
  {
   "title": "Load Balancers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 24 },
   "targets": [
    { "expr": "count(aws_alb_info)" }
   ]
  },
  {
   "title": "Target groups",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 24 },
   "targets": [
    {
     "expr": "count(aws_alb_tg_healthy_host_count_average)"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_active_connection_count_sum)",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Bytes processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_processed_bytes_sum)",
     "legendFormat": "Bytes processed"
    }
   ]
  },
  {
   "title": "Rules Evaluated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_rule_evaluations_sum)",
     "legendFormat": "Rules"
    }
   ]
  },
  {
   "title": "LCUs Consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(aws_alb_consumed_lcus_sum)", "legendFormat": "LCU" }
   ]
  },
  {
   "title": "Processed Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(aws_alb_request_count_sum)", "legendFormat": "Processed requests" }
   ]
  },
  {
   "title": "2XX Responses by Target Groups ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_tg_httpcode_target_2_xx_count_sum)",
     "legendFormat": "2XX"
    },
    { "legendFormat": "Active connections" }
   ]
  },
  {
   "title": "3XX Responses by Target Groups ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_tg_httpcode_target_3_xx_count_sum)",
     "legendFormat": "3XX"
    },
    { "legendFormat": "Active connections" }
   ]
  }
 ]
}