{
 "title": "consul",
 "description": "consul",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Raft commit time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(consul_raft_commitTime_sum[5m]) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Last Contacted Leader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact{ quantile=\"0.9\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Election Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum( rate(consul_raft_state_candidate[5m] ))",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "sum( rate(consul_raft_state_leader[5m] ))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "KV Store update time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(consul_kvs_apply_sum[5m]) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Transaction operation time\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(consul_txn_apply_sum[5m]) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Autopilot Fault Tolerance\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "consul_autopilot_failure_tolerance",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Autopilot Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "consul_autopilot_healthy", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Client RPC IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(consul_client_rpc[5m])", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Client RPC Error Rate\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(consul_client_rpc_failed[5m]) / rate(consul_client_rpc[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Client RPC Rate Limit Reached\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(consul_client_rpc_exceeded[5m]) / rate(consul_client_rpc[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Server RPC IOPS\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(consul_rpc_query[5m])", "legendFormat": "{{ handler }}" },
    { "expr": "rate(consul_rpc_request[5m])", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Server RPC Error Rate\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(consul_rpc_request_error[5m]) / rate(consul_rpc_request[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Server RPC Blocking requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(consul_rpc_cross_dc[5m])", "legendFormat": "{{ handler }}" },
    {
     "expr": "rate(consul_rpc_queries_blocking[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Garbage collection pause time (p90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(consul_runtime_gc_pause_ns{ quantile=\"0.9\"})",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Garbage collection pause time average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(rate(consul_runtime_gc_pause_ns_sum[5m] ) )",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "consul_consul_cache_fetch_success/(consul_consul_cache_fetch_success+ ignoring(result_not_modified) group_leftconsul_consul_cache_fetch_error)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Snapshot Restoration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "consul_raft_leader_oldestLogAge > 0",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "consul_raft_rpc_instSnapshot{ quantile=\"0.99\"}",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "consul_raft_fsm_lastRestoreDuration > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache Eviction Rate\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "consul_consul_cache_evict_expired/(consul_consul_cache_evict_expired+ consul_consul_cache_entries_count)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cache Bypass Rate\n",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "consul_consul_cache_bypass/( (\tconsul_consul_cache_bypass +\tconsul_consul_cache_fetch_error ) + ignoring(result_not_modified) group_right consul_consul_cache_fetch_success)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Raft transactions rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(consul_raft_apply[5m]) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "min(consul_autopilot_healthy)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "License expiration\n",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(consul_system_licenseExpiration)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Transaction timing",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "These metrics indicate how long it takes to complete write operations in various parts of the Consul cluster. Generally these should all be fairly consistent and no more than a few milliseconds. Sudden changes in any of the timing values could be due to unexpected load on the Consul servers, or due to problems on the servers themselves."
   }
  },
  {
   "title": "Leadership",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "Under normal situations, a Consul cluster should have a stable leader. If there are frequent elections or leadership changes (flapping leadership), it would likely indicate network issues between the Consul servers, or that the Consul servers themselves are unable to keep up with the load.\n"
   }
  },
  {
   "title": "Garbage collection",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 55 },
   "options": {
    "content": "GC pauses are \"stop-the-world\" events, meaning that all runtime threads are blocked until GC completes. Normally these pauses last only a few nanoseconds, but if memory usage is high, the Go runtime may GC so frequently that it starts to slow down Consul."
   }
  },
  {
   "title": "Network activity - RPC Count",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "These measurements indicate the current load created from a Consul agent, including when the load becomes high enough to be rate limited. A high RPC count, especially from the 'RPC Exceeded' panel meaning that the requests are being rate-limited, could imply a misconfigured Consul agent."
   }
  },
  { "title": "Health", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "Cache", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 }, "options": { "content": "# Cache" } }
 ]
}